/* ==========================================================================
   content.js — EDUCATIONAL_CONTENT: lessons + quizzes
   Lesson fields: analogy, simple, tech, ex (worked example), risks (cost / what can
   go wrong), check[] (what to check), mistakes[]. Examples are illustrative only.
   ========================================================================== */
window.FOS = window.FOS || {};
(function () {
  'use strict';
  const LESSONS = {}, QUIZ = {};
  const L = (mod, title, o) => { (LESSONS[mod] = LESSONS[mod] || []).push(Object.assign({ id: mod + '-' + ((LESSONS[mod] || []).length + 1), t: title }, o)); };
  const Q = (mod, q) => { (QUIZ[mod] = QUIZ[mod] || []).push(q); };
  const mc = (q, o, a, e, w, rel) => ({ t: 'mc', q, o, a, e, w, rel });
  const tf = (q, a, e, w, rel) => ({ t: 'tf', q, o: ['True', 'False'], a: a ? 0 : 1, e, w, rel });
  const calc = (q, a, tol, e, rel) => ({ t: 'calc', q, a, tol, e, w: 'Use the formula shown in the related calculator.', rel });

  /* ---------------- Money basics ---------------- */
  L('basics', 'What is money — and why does inflation shrink it?', { analogy: 'Money is an ice cube on a warm table: even if you never touch it, inflation slowly melts what it can buy.', simple: 'Money is a tool to swap effort for things. Prices usually rise each year, so the same ₹100 buys less later.', tech: 'Inflation erodes purchasing power: future cost = cost × (1+i)^t. India has often seen roughly 5–6% a year over long periods. Real return ≈ (1+nominal)/(1+inflation) − 1.', ex: '₹1,000 of groceries at 6% inflation costs ≈ ₹1,338 in 5 years and ≈ ₹1,791 in 10. A savings account at 3.5% grows ₹1,000 to ≈ ₹1,410 in 10 years — more rupees, less buying power.', risks: 'Idle cash loses real value every year. The cost is invisible because the balance still grows.', check: ['Is my money growing faster than inflation?', 'What is the after-tax, after-inflation return?'], mistakes: ['Judging savings only by the balance number', 'Comparing today\'s ₹ with future ₹ without adjusting'] });
  L('basics', 'Time value of money & compounding', { analogy: 'A snowball rolling downhill: the bigger it gets, the more snow it picks up per roll.', simple: 'A rupee today is worth more than a rupee later, and money that earns returns on its own returns grows faster over time.', tech: 'A = P(1 + r/n)^(nt). PV = FV/(1+r)^t. Time matters more than the amount: compounding is slow in years 1–5 and dramatic in years 20–30.', ex: '₹1,00,000 at 12% a year becomes ≈ ₹9.6 lakh in 20 years and ≈ ₹30 lakh in 30. ₹1 lakh invested at 25 beats ₹2 lakh invested at 35 (≈ ₹30 lakh vs ≈ ₹19 lakh at 65, same 12% assumption).', risks: 'The same maths works against you on debt: unpaid credit-card balances compound at ~3–4% a month.', check: ['How long can this money stay untouched?', 'What are the fees? They compound too.'], mistakes: ['Waiting for a “big enough” amount before starting', 'Ignoring that returns are assumptions, not guarantees'] });
  L('basics', 'Income: gross, net, CTC, take-home', { analogy: 'CTC is the price tag of hiring you; take-home is what actually lands in your pocket.', simple: 'Your offer letter shows CTC. Employer PF, gratuity, insurance, tax and your own PF reduce what reaches your bank.', tech: 'Gross salary = CTC − employer contributions. Net (take-home) = gross − employee PF − income tax − professional tax − other deductions. Variable pay/bonus is not guaranteed.', ex: 'A ₹12 lakh CTC often means roughly ₹85,000–₹95,000 in hand per month depending on structure and regime. Use the Salary Analyzer.', risks: 'Budgeting on CTC overstates your spending power by 15–30%.', check: ['Is variable pay guaranteed?', 'What are PF and tax deductions?'], mistakes: ['Planning EMIs on gross salary', 'Treating bonus as regular income'] });
  L('basics', 'Expenses and saving', { analogy: 'Fixed expenses are the walls of the house; variable expenses are the furniture you can rearrange.', simple: 'Fixed costs (rent, EMI) repeat every month; variable ones (food, fuel) change. Essentials must be paid; discretionary ones are choices.', tech: 'Classify every rupee: fixed/variable, essential/discretionary, recurring/one-time. Savings = income − expenses. Emergency fund = liquid reserve of several months of essentials.', ex: '₹60,000 income: rent ₹12,000, food ₹6,000, transport ₹4,000, utilities ₹3,000 are needs (₹25,000); subscriptions and entertainment ₹4,000 are wants; ₹15,000 + ₹5,000 go to investing and emergency fund.', risks: 'Small recurring expenses (₹200/day = ₹72,000/year) are the easiest to overlook.', check: ['Which expenses repeat automatically?', 'Which could I pause for a month?'], mistakes: ['Not tracking small expenses', 'Keeping savings in the same account as spending money'] });
  L('basics', 'Risk, return, liquidity and diversification', { analogy: 'Choosing a vehicle for a journey: a bicycle (FD) is slow but arrives; a race car (stocks) is fast but can crash.', simple: 'Every option has three dials: risk (can it fall?), return (what does it earn?), liquidity (how fast is cash available?). Higher return usually needs higher risk.', tech: 'Volatility = size of price swings. Diversification spreads risk across assets that do not move together. Time horizon decides how much volatility you can afford.', ex: '₹1 lakh for 5 years: savings 3.5% → ₹1,18,769; FD 7.5% → ₹1,44,995; equity fund ~12% average → ₹1,76,234 (but could be below ₹1 lakh in a bad window).', risks: 'Anyone promising high return with no risk is lying or scamming.', check: ['When do I need the money?', 'What would I do if it fell 20%?'], mistakes: ['Chasing last year\'s best performer', 'Putting all savings in one basket'] });
  Q('basics', mc('What will something costing ₹500 today cost in ~12 years at 6% inflation (Rule of 72)?', ['₹500', '₹750', '₹1,000', '₹1,500'], 2, 'At 6%, prices double about every 72 ÷ 6 = 12 years. Exact: 500×1.06^12 ≈ ₹1,006.', '₹750 is a 50% rise; ₹1,500 is a tripling.', 'inflation'));
  Q('basics', tf('₹1 lakh invested early can beat ₹2 lakh invested much later, at the same return.', true, 'Compounding rewards time. Over 30 vs 20 years at 12%, ≈₹30 lakh beats ≈₹19 lakh.', 'Amount matters, but time multiplies it.', 'compound'));
  Q('basics', calc('A sum grows at 10% for 2 years, compounded yearly. ₹1,00,000 becomes? (₹)', 121000, 50, '100000 × 1.1 × 1.1 = 121,000.', 'compound'));

  /* ---------------- Income & salary ---------------- */
  L('income', 'Reading your salary slip', { analogy: 'A salary slip is a receipt showing where each rupee of your pay went before it reached you.', simple: 'Earnings (basic, HRA, allowances) minus deductions (PF, tax, professional tax) equals net pay.', tech: 'Basic salary drives PF (12%) and gratuity. Tax depends on regime, deductions and other income. TDS is advance tax; you reconcile at filing.', ex: 'Basic ₹40,000 → employee PF ₹4,800 and employer PF ₹4,800 going into EPF each month — ₹9,600 building a retirement pool at ~8%.', risks: 'A low basic reduces PF/gratuity; a high variable share makes income uncertain.', check: ['Fixed vs variable split', 'PF, gratuity, insurance inside CTC', 'Tax regime chosen'], mistakes: ['Ignoring EPF/VPF as a savings tool', 'Not checking Form 16 / AIS against your slips'] });
  Q('income', mc('Which best describes take-home pay?', ['CTC ÷ 12', 'Gross minus deductions like PF and tax', 'Basic salary only', 'Bonus plus CTC'], 1, 'Take-home = gross − deductions (employee PF, tax, professional tax etc.).', 'CTC ÷ 12 includes employer contributions you never receive in cash.', 'salary'));
  Q('income', tf('You should plan your EMI using CTC.', false, 'Plan on take-home, because CTC includes amounts you do not receive monthly.', 'Bonus and employer PF are not available for monthly bills.', 'salary'));

  /* ---------------- Budgeting ---------------- */
  L('budgeting', 'Giving every rupee a job', { analogy: 'A budget is a plan for your money, not a punishment — like a GPS route, you can reroute anytime.', simple: 'List income, list categories, assign amounts, compare with reality monthly.', tech: '50/30/20: needs/wants/savings. Zero-based: income − allocations = 0. Pay-yourself-first: transfer savings on payday. Envelope: fixed amount per category; stop at empty.', ex: '₹60,000: needs ₹30,000, wants ₹18,000, savings ₹12,000 under 50/30/20. In a high-rent city needs might be 60% — adjust and still save something.', risks: 'An unrealistic budget is abandoned in weeks. Forgetting annual expenses (insurance, fees) causes shocks.', check: ['Did I include yearly bills ÷ 12?', 'Do I have a buffer category?'], mistakes: ['Copying someone else\'s percentages', 'Never reviewing actual spending'] });
  Q('budgeting', mc('In a zero-based budget, what should "income minus allocated amounts" equal?', ['Positive surplus', 'Zero', 'Negative', '20% of income'], 1, 'Every rupee is assigned, including savings.', 'A leftover surplus is unassigned money.', 'savingsrate'));
  Q('budgeting', calc('Income ₹60,000; expenses ₹45,000. What is the savings rate (%)?', 25, 0.1, '(60,000−45,000) ÷ 60,000 × 100 = 25%.', 'savingsrate'));

  /* ---------------- Spending ---------------- */
  L('spending', 'The real price of small, repeated spending', { analogy: 'A tiny leak in a tank: one drop is nothing, but it empties the tank over a year.', simple: 'Multiply any repeating purchase by 30, 365 and 10 years before deciding.', tech: 'Annualised cost = price × frequency × 12. Opportunity cost = future value of the same monthly amount under a hypothetical return, shown with assumptions.', ex: '₹200/day = ₹6,000/month = ₹72,000/year = ₹7.2 lakh in 10 years of spending. At a hypothetical 10% it could be ≈ ₹12 lakh if invested instead (illustrative only).', risks: 'Habits are invisible because each payment is small. Credit-card payment adds interest if you carry a balance.', check: ['Need, want or habit?', 'Annual cost', 'Cheaper substitute'], mistakes: ['Only comparing price, not frequency', 'Treating subscriptions as “free” after signup'] });
  Q('spending', calc('₹200 per day. What is the yearly cost (₹, use 365 days)?', 73000, 100, '200 × 365 = 73,000 (≈ ₹72,000 if using 30-day months).', 'subscription'));
  Q('spending', tf('Opportunity cost shows guaranteed returns you missed.', false, 'It is a hypothetical calculation under assumptions, never a guarantee.', 'Returns can be lower or negative.', 'oppcost'));

  /* ---------------- Banking ---------------- */
  L('banking', 'Savings, FD, RD — and payment rails', { analogy: 'A savings account is your wallet\'s safer cousin; an FD is the disciplined sibling who locks money in for more interest.', simple: 'Savings = instant access, low interest. FD = lump sum locked for a fixed rate. RD = monthly deposits with FD-like safety.', tech: 'FD maturity = P(1+r/4)^(4t) in most Indian banks (quarterly compounding). DICGC insures deposits up to ₹5 lakh per depositor per bank (verify). UPI/IMPS are instant; NEFT batches; RTGS for large amounts. Interest is taxable at slab.', ex: '₹1 lakh at 7.5% for 5 years → ₹1,44,995. ₹5,000/month RD for 3 years at 7% → ≈ ₹2,01,848 on ₹1.8 lakh deposited.', risks: 'Early withdrawal penalty (≈0.5–1%), inflation risk, minimum-balance fees, TDS.', check: ['Minimum balance and charges', 'Premature-withdrawal penalty', 'Nominee added', 'Post-tax, post-inflation return'], mistakes: ['Locking emergency money in a long FD', 'Choosing FD tenure to chase a rate instead of matching the need'] });
  Q('banking', mc('For money needed in exactly 8 months, which fits best?', ['5-year FD for the highest rate', 'An FD or liquid option of about 8–9 months', 'Crypto', 'Stocks'], 1, 'Match tenure to need; breaking a long FD costs a penalty.', 'Long FDs and volatile assets can force a loss when the bill is due.', 'fd'));
  Q('banking', tf('Bank FDs commonly compound interest quarterly.', true, 'That is the usual Indian bank convention.', 'Simple interest is not what cumulative FDs use.', 'fd'));

  /* ---------------- Credit cards ---------------- */
  L('cards', 'Credit cards: a short-term loan with rewards', { analogy: 'A credit card is a free loan only if you repay the entire bill on time — otherwise it is one of the costliest loans you can hold.', simple: 'You spend now, pay by the due date. Pay in full → no interest. Pay the minimum → interest on the rest.', tech: 'Billing cycle ≈ 30 days; statement date; due date ~15–20 days later. Minimum due is a small % of balance. APR ~36–45%: monthly rate 3–3.75%. Fees: annual, late, cash advance, forex, GST.', ex: '₹1 lakh balance at 42% paying ₹5,000 fixed takes years and costs lakhs in interest; the simulator shows the exact months and total. Cash advances charge interest from day one.', risks: 'Minimum-due trap, overspending, utilization hurting credit score, fee creep.', check: ['Can I pay the full bill?', 'Autopay for total due', 'Reward value vs annual fee'], mistakes: ['Paying only the minimum', 'Withdrawing cash on the card', 'Converting everything to EMI without checking the fee'] });
  L('cards', 'Rewards and cashback — are they worth it?', { analogy: 'Rewards are a discount on the price of a product that can bill you more than it saves.', simple: 'A 1–5% reward is wiped out by one month of interest at ~3.5%.', tech: 'Net value = rewards − annual fee − interest − forex/other fees. Compare only on spending you would do anyway.', ex: '₹30,000/month at 2% = ₹7,200/year rewards; annual fee ₹1,500 → net ₹5,700. One unpaid ₹30,000 bill at 3.5% costs ₹1,050 in a month.', risks: 'Rewards encourage spending beyond plan.', check: ['Reward rate on real categories', 'Expiry of points', 'Caps and exclusions'], mistakes: ['Spending to earn points', 'Ignoring fuel/rent exclusions'] });
  Q('cards', mc('What does paying only the minimum due typically do?', ['Clears the bill', 'Avoids late fee but interest accrues on the rest', 'Removes interest', 'Improves your score instantly'], 1, 'Minimum due avoids the late fee; the unpaid balance keeps charging interest.', 'It does not clear the bill or stop interest.', 'cardpay'));
  Q('cards', calc('Limit ₹2,00,000, outstanding ₹60,000. Credit utilization (%)?', 30, 0.1, '60,000 ÷ 2,00,000 = 30%.', 'utilization'));

  /* ---------------- Credit score ---------------- */
  L('score', 'How credit scores work', { analogy: 'A credit score is a repayment report card lenders read before trusting you.', simple: 'Paying on time, using a small part of your limit, and keeping old accounts open generally help.', tech: 'Factors: payment history, credit utilization, credit age, credit mix, hard inquiries. Scores range ~300–900. Bureaus differ and models are proprietary; the list is a guide, not a formula.', ex: 'Utilization of 30% (₹30,000 of ₹1 lakh) is commonly cited as a guideline. Many applications in a short time create hard inquiries.', risks: 'Errors in reports, identity theft, guarantor liability.', check: ['Free annual credit report check', 'Dispute wrong entries', 'Autopay'], mistakes: ['Closing your oldest card', 'Applying for many loans at once'] });
  Q('score', mc('Which habit usually helps a credit profile?', ['Missing due dates', 'Paying on time and keeping utilization modest', 'Maxing out cards', 'Applying for many cards at once'], 1, 'Payment history and utilization are major factors.', 'The others typically hurt.', 'utilization'));
  Q('score', tf('Credit scoring is a single public formula.', false, 'Models are proprietary and more complex than any summary.', 'Our calculator only shows utilization.', 'utilization'));

  /* ---------------- Loans ---------------- */
  L('loans', 'The anatomy of any loan', { analogy: 'A loan is renting money: the rent is interest, plus service charges.', simple: 'Principal + interest + fees over a tenure. The lower the EMI, the longer you usually pay.', tech: 'Secured (home, car, gold) vs unsecured (personal, card). Key checks: rate type (fixed/floating), processing fee, GST, insurance bundling, prepayment/foreclosure charges, penalties, effective APR.', ex: '₹5 lakh personal loan at 12% for 3 years with 2% + GST fee: EMI ≈ ₹16,607; fees ≈ ₹11,800; total cost noticeably above the stated rate. Use “Loan true cost”.', risks: 'EMI stress if income falls, floating-rate increases, default harming credit and collateral.', check: ['Total repayment', 'Effective rate', 'Prepayment terms', 'EMI as % of income'], mistakes: ['Comparing EMI only', 'Taking a loan for consumption that a short wait would avoid'] });
  L('loans', 'Instant-loan apps and the warning signs', { analogy: 'A payday app loan is a taxi meter running at 10× speed.', simple: 'Very fast approval, tiny tenure, huge fees and aggressive recovery.', tech: 'Use only RBI-registered lenders; check the app in the lender\'s registered list; insist on a key fact statement (KFS).', ex: 'A ₹10,000 loan for 15 days with ₹2,000 fees equals an effective annual cost of several hundred percent.', risks: 'Harassment, data misuse, debt spirals.', check: ['RBI registration', 'Permissions requested', 'APR'], mistakes: ['Granting contacts/gallery access', 'Borrowing from one app to repay another'] });
  Q('loans', mc('Which is the best measure to compare two loans?', ['The EMI alone', 'Total repayment and effective rate including fees', 'The lender\'s advertising', 'The shortest form'], 1, 'Fees change the true cost.', 'A low EMI can hide a long tenure.', 'loancost'));
  Q('loans', tf('A longer tenure lowers EMI but usually increases total interest.', true, 'Interest accrues for more months.', 'There is no free lunch.', 'emi'));

  /* ---------------- EMI ---------------- */
  L('emi', 'How EMI works', { analogy: 'EMI is a see-saw: early on most goes to interest; later most goes to principal.', simple: 'Same instalment every month, but the split changes.', tech: 'EMI = P·r·(1+r)^n / ((1+r)^n − 1), r = annual/12/100. Interest(month) = opening balance × r. Prepaying principal cuts future interest; the earlier, the bigger the saving. If r = 0, EMI = P/n.', ex: '₹10 lakh at 10% for 5 years → EMI ≈ ₹21,247, total interest ≈ ₹2.75 lakh. Add ₹5,000 extra per month to finish years sooner — see the Prepayment Simulator.', risks: 'Floating rates change EMI/tenure; prepayment charges on some loans.', check: ['Rate type', 'Prepayment allowed?', 'Opportunity cost of prepaying'], mistakes: ['Prepaying cheap debt while carrying expensive debt', 'Forgetting processing fee'] });
  L('emi', 'Snowball vs avalanche', { analogy: 'Avalanche attacks the costliest debt first; snowball clears the smallest first for motivation.', simple: 'Same total payment, different order.', tech: 'Avalanche minimises total interest; snowball reduces the number of debts fastest. The math difference depends on rate gaps.', ex: 'Three debts at 36%, 14% and 9%: avalanche targets the 36% one first and generally pays less interest overall.', risks: 'Behavioural: losing motivation on the hardest-first path.', check: ['List balances and rates', 'Minimums on all debts'], mistakes: ['Not stopping new card spend while repaying'] });
  Q('emi', calc('EMI for ₹1,00,000 at 0% for 10 months (₹)?', 10000, 1, 'Zero interest: principal ÷ months = 10,000.', 'emi'));
  Q('emi', mc('Which debt should the avalanche method target first?', ['Smallest balance', 'Highest interest rate', 'Oldest debt', 'Lowest EMI'], 1, 'Highest rate costs the most per rupee.', 'Smallest balance is the snowball method.', 'debtpayoff'));

  /* ---------------- Insurance ---------------- */
  L('insurance', 'Insurance is protection, not investment', { analogy: 'A helmet protects your head; a savings jar is a terrible helmet and a helmet is a terrible place to store savings.', simple: 'Insurance moves a rare, big loss from you to an insurer for a small premium.', tech: 'Terms: premium, sum insured, deductible, co-pay, waiting period, exclusions, sub-limits, renewal, portability, claim ratio. Term = pure life cover; health = hospital costs; motor = third-party is mandatory.', ex: 'A healthy 30-year-old may pay roughly ₹700–1,000/month for ₹1 crore term cover (illustrative). A combined investment-insurance plan at similar premium may give a fraction of the cover and mediocre growth.', risks: 'Claim rejection from exclusions/non-disclosure, premium hikes, under-insurance.', check: ['Exclusions & waiting period', 'Co-pay/sub-limits', 'Network hospitals', 'Renewal terms'], mistakes: ['Relying only on employer cover', 'Hiding pre-existing conditions', 'Buying for tax saving only'] });
  Q('insurance', tf('Co-pay means you pay a share of each claim.', true, 'A co-pay is a percentage of the claim borne by the policyholder.', 'It is not the premium.', 'cover'));
  Q('insurance', mc('Why read exclusions before buying?', ['They list what will NOT be paid', 'They reduce premium automatically', 'They are advertising', 'They do not matter'], 0, 'Exclusions define what is not covered.', 'Claims get rejected on them.', 'cover'));

  /* ---------------- Emergency ---------------- */
  L('emergency', 'Your buffer between a bad month and a bad decision', { analogy: 'A spare tyre: you hope not to need it, and you are glad it is there.', simple: 'Liquid money for essentials when income stops or a surprise hits.', tech: 'Months of cover = liquid emergency savings ÷ (essential expenses + debt payments). More months may suit variable income, dependents or no health insurance; fewer may suit stable income with other supports.', ex: '₹30,000 essentials + ₹10,000 EMIs → 6 months = ₹2.4 lakh. Keep in savings/liquid funds, not in volatile assets.', risks: 'Using it for wants, or investing it and finding it down 30% when needed.', check: ['Where is it held?', 'Do I replenish after use?'], mistakes: ['Counting the FD you cannot break', 'Treating it as a one-time task'] });
  Q('emergency', mc('Where is an emergency fund best kept?', ['In small-cap stocks', 'In instantly accessible low-risk places', 'In crypto', 'In real estate'], 1, 'Liquidity and capital safety come first.', 'Volatile or illiquid assets can fail you at the wrong time.', 'emergency'));
  Q('emergency', calc('Essentials ₹30,000 and EMIs ₹10,000 per month. 6 months of cover (₹)?', 240000, 1, '(30,000 + 10,000) × 6 = 2,40,000.', 'emergency'));

  /* ---------------- Scams ---------------- */
  L('scams', 'Scam patterns', { analogy: 'A registered chit fund is a neighbours\' savings circle; an unregistered one with "guaranteed 3% a month" is a wolf in sheep\'s clothing.', simple: 'Scams promise certainty, create urgency, and ask for secrets or fees.', tech: 'Ponzi: pays old investors with new money. Pyramid: income from recruitment. Phishing/vishing: steal OTPs or credentials. UPI collect fraud: you approve a debit thinking you receive. 3% monthly = 36%+ a year — not a sustainable legitimate return.', ex: 'A relative pitches "3% a month guaranteed, no risk." First question: is it registered (Registrar of Chits / SEBI / RBI) and can I see the registration?', risks: 'Total loss; legal trouble if you recruit others.', check: ['Independent verification', 'Regulator registry', 'Never share OTP/PIN'], mistakes: ['Trusting screenshots of profits', 'Calling numbers found in search ads'] });
  Q('scams', mc('A caller asks for the OTP "to verify your account". What should you do?', ['Share it quickly', 'Never share; end the call and contact the bank via official channels', 'Share half', 'Ask a friend to share'], 1, 'OTPs authorise transactions; banks never need them from you.', 'Any sharing can let a thief move money.', 'cryptoscen'));
  Q('scams', tf('A guaranteed high return with no risk is a red flag.', true, 'Risk and return are linked; guarantees of high returns are typical of scams.', 'Legit high-return products disclose risks.', 'cryptoscen'));

  /* ---------------- Investing ---------------- */
  L('investing', 'Before you invest a single rupee', { analogy: 'You do not build the second floor before the foundation. Investing is the second floor.', simple: 'First: emergency fund, health insurance, term cover if others depend on you, and clearing high-interest debt. Then invest.', tech: 'Paying off 36% debt is a guaranteed 36% “return”. Match time horizon: <3 years low-volatility; 3–7 years mixed; 7+ years equity-heavy possible. Risk profile = time horizon + how you would react to a 20% fall.', ex: '₹50,000 card debt at 36% vs ₹50,000 invested at ~12%: after a year you are ≈ ₹12,000 worse off by investing while the debt grows.', risks: 'Investing without a buffer forces selling at the worst time.', check: ['Time horizon', 'Reaction to a 20% fall', 'Fees & taxes', 'Registration of seller'], mistakes: ['Chasing tips', 'All-in on one asset'] });
  L('investing', 'Asset classes compared', { analogy: 'A menu: each dish (asset) has a different taste (return), heat (risk) and speed of service (liquidity).', simple: 'Savings and FDs are steady; bonds pay interest; equity grows but swings; gold is a stabiliser; crypto is highly speculative.', tech: 'Savings ~3–4%; FD ~6.5–7.5%; PPF ~7% tax-free; equity funds long-run ~10–14% average (not guaranteed); gold ~7–9% with swings; real estate illiquid. These are historical ranges, not promises.', ex: 'Simple default discussed in the guide: equity % ≈ 100 − age, adjusted to comfort — at 30 that is ~70% equity. It is a rule of thumb, not advice.', risks: 'Concentration, chasing returns, ignoring taxes.', check: ['Taxes on gains', 'Lock-in', 'Expense ratios'], mistakes: ['Ignoring rebalancing', 'Confusing average with guarantee'] });
  Q('investing', mc('You have no emergency fund and 36% credit-card debt. Where might the next ₹50,000 do the most guaranteed good?', ['Equity fund', 'Repaying the card debt', 'Crypto', 'Another card'], 1, 'Repaying 36% debt saves 36% a year with certainty.', 'Expected equity returns are uncertain and lower.', 'allocation'));
  Q('investing', tf('High return and zero risk together is realistic.', false, 'Risk and return are linked.', 'That combination is a scam signal.', 'allocation'));

  /* ---------------- Mutual funds ---------------- */
  L('mutualfunds', 'Mutual funds, SIPs and the cost of fees', { analogy: 'Thousands of people hire one skilled chef to cook one big meal and share it.', simple: 'A fund pools money; you own units priced at NAV. SIP = fixed monthly purchase; lumpsum = one go.', tech: 'Expense ratio is deducted daily from NAV. Direct plans have lower expense ratios than regular plans (no distributor commission). Index funds track an index; tracking error shows deviation. SWP withdraws regularly; STP moves money between funds gradually. Exit load applies on early redemption.', ex: '₹10,000/month for 25 years: at 12% ≈ ₹1.9 crore; at 11% (1% higher fee) ≈ ₹1.6 crore — a ≈ ₹30 lakh difference from fee alone (illustrative). Try the Fee Impact calculator.', risks: 'NAV falls, manager/style risk, credit risk in debt funds, taxes.', check: ['Riskometer & category', 'Direct vs regular', 'Exit load', 'Tax rules by category'], mistakes: ['Stopping SIPs in a fall', 'Comparing only 1-year returns'] });
  Q('mutualfunds', mc('What does a higher expense ratio do to your returns?', ['Nothing', 'Reduces net returns every year, compounding over time', 'Increases returns', 'Only matters on exit'], 1, 'It is deducted continuously.', '1% a year is large over decades.', 'fees'));
  Q('mutualfunds', calc('₹10,000 SIP for 1 month at any return: the amount invested is (₹)?', 10000, 0, 'One instalment = ₹10,000.', 'sip'));

  /* ---------------- Stocks ---------------- */
  L('stocks', 'Stocks: ownership, ratios and the limits of ratios', { analogy: 'Buying a stock is buying a small stake in a restaurant — and you must understand how it earns.', simple: 'A share is a piece of ownership. Price changes with expectations about future profits.', tech: 'EPS = profit ÷ shares. P/E = price ÷ EPS. P/B = price ÷ book value/share. ROE = profit ÷ equity. Dividend yield = dividend ÷ price. Free cash flow = operating cash flow − capex. Drawdown = peak-to-trough fall. Ratios describe; they do not predict.', ex: 'Price ₹500, EPS ₹25 → P/E 20. One company falling 50% hits a single-stock portfolio by 50%, but may be 1–2% of a diversified fund.', risks: 'Company-specific failure, tips, over-concentration, leverage.', check: ['Can I explain the business?', 'Debt & cash flow', 'Position size'], mistakes: ['Buying on social-media tips', 'Treating a low P/E as automatically cheap'] });
  L('stocks', 'Trading (intraday & F&O): read first', { analogy: 'Less investing, more poker table where the house earns from every hand.', simple: 'Short-term bets with leverage amplify losses.', tech: 'A SEBI study found roughly 9 in 10 individual F&O traders lost money over the study period (verify latest). Brokers earn on volume.', ex: '“Guaranteed ₹5,000/day from tips” is a classic scam pitch.', risks: 'Total loss; losses beyond capital with leverage.', check: ['Capital you can lose completely', 'Separate from goals'], mistakes: ['Revenge trading', 'Borrowing to trade'] });
  Q('stocks', calc('Price ₹500, EPS ₹25. P/E ratio?', 20, 0.01, '500 ÷ 25 = 20.', 'pe'));
  Q('stocks', tf('A ratio such as P/E tells you whether a stock will rise.', false, 'It describes valuation versus earnings, not the future price.', 'No ratio predicts price moves.', 'pe'));

  /* ---------------- Bonds ---------------- */
  L('bonds', 'Bonds: coupon, yield, duration', { analogy: 'Lending money to the government or a company, who pays rent (coupon) for using it.', simple: 'Face value is repaid at maturity; coupon is the interest; price moves inversely to market yields.', tech: 'Price = PV of coupons + PV of face. Duration measures sensitivity: modified duration 5 ≈ 5% price fall per 1% yield rise. Risks: credit/default, interest-rate, reinvestment, liquidity.', ex: 'A ₹1,000 bond with 8% coupon and 5 years when market yield rises to 9% trades below ₹1,000.', risks: 'Credit downgrades; selling before maturity at a loss.', check: ['Issuer rating & verification', 'Tax', 'Liquidity'], mistakes: ['Chasing the highest yield without checking default risk'] });
  Q('bonds', mc('When market yields rise, existing bond prices generally…', ['Rise', 'Fall', 'Stay the same', 'Double'], 1, 'Old coupons look less attractive, so prices fall.', 'Price and yield move in opposite directions.', 'bond'));
  Q('bonds', tf('A higher-yield bond may carry more credit risk.', true, 'Yield often compensates for risk.', 'Higher yield is not free.', 'bond'));

  /* ---------------- Gold ---------------- */
  L('gold', 'Gold: a stabiliser, not a growth engine', { analogy: 'Insurance for your portfolio: it often holds ground when stocks fall.', simple: 'You can own gold as jewellery, coins/bars, ETFs/funds, digital gold or (when available) sovereign bonds.', tech: 'Costs: making charges, GST, storage, expense ratio, spread. Jewellery buy-back deductions can be 5–25%. Sovereign gold bonds paid extra interest with tax benefit at maturity for earlier issues — verify current availability.', ex: '₹5 lakh in jewellery with 12% making + 3% GST starts ~13% behind the gold price before any growth.', risks: 'Flat price for years, purity, theft, taxes.', check: ['Making charges', 'Hallmark', 'Buy-back policy'], mistakes: ['Treating jewellery as pure investment'] });
  Q('gold', mc('Which usually has the lowest ongoing holding cost?', ['Jewellery in a locker', 'Gold ETF (expense ratio)', 'Loose coins at home', 'All identical'], 1, 'An ETF has a small expense ratio but no making charge or locker.', 'Physical storage adds cost and risk.', 'goldcalc'));
  Q('gold', tf('Making charges are part of the real cost of jewellery.', true, 'They reduce what you get back.', 'They are rarely recovered on resale.', 'goldcalc'));

  /* ---------------- Govt & post office ---------------- */
  L('govt', 'Government savings schemes', { analogy: 'The country itself guarantees your deposit — the boring, safe backbone.', simple: 'PPF, NSC, SSY, SCSS, KVP: sovereign-backed, rates reset by government.', tech: 'PPF: deposit up to ₹1.5 lakh/yr, 15-year lock-in, annual compounding, tax-advantaged. SSY: for a girl child. SCSS: for seniors with quarterly payout. Rates and limits change — see the configuration with source and verify date.', ex: '₹1.5 lakh/year in PPF at 7.1% for 20 years ≈ ₹66.6 lakh on ₹30 lakh deposited; all gain is tax-free under current treatment (verify).', risks: 'Low liquidity, rate resets, inflation risk.', check: ['Current rate on official source', 'Lock-in', 'Tax treatment'], mistakes: ['Comparing headline rates while ignoring tax'] });
  L('postoffice', 'Post Office schemes', { analogy: 'Post Office schemes are the neighbourhood door to the same sovereign guarantee.', simple: 'Savings account, time deposit, recurring deposit, Monthly Income Scheme and certificates.', tech: 'Interest is set quarterly. POMIS/SCSS pay out regularly; TDs compound quarterly. Each has limits, lock-ins and tax rules in the configuration.', ex: 'A monthly-income scheme suits regular cash flow; a 5-year TD suits a fixed goal.', risks: 'Early-exit penalties and taxable interest.', check: ['Rates', 'Limits', 'Premature closure terms'], mistakes: ['Ignoring the TDS/tax on interest'] });
  Q('govt', mc('Why can PPF beat a higher-rate FD in your pocket?', ['It cannot', 'Its return is tax-free while FD interest is taxed at your slab', 'It is riskier', 'It has no lock-in'], 1, 'Compare post-tax returns.', 'FD interest is fully taxable.', 'ppf'));
  Q('govt', tf('Scheme interest rates never change.', false, 'They are reset periodically; always check the official source.', 'That is why they sit in configuration.', 'ppf'));
  Q('postoffice', mc('Where should you verify current post office rates?', ['Social media', 'India Post / Ministry of Finance official sources', 'A friend', 'Any blog'], 1, 'Official sources have the current rates.', 'Others may be outdated.', 'rd'));
  Q('postoffice', tf('Post office schemes are backed by the government.', true, 'They are sovereign-backed small-savings instruments.', 'Still check limits & lock-in.', 'rd'));

  /* ---------------- Retirement ---------------- */
  L('retirement', 'How much is enough?', { analogy: 'Retirement is a long trip with no salary; you need a fuel tank sized to the distance, and fuel prices keep rising.', simple: 'Estimate future expenses, multiply by years in retirement, then see if your savings path gets there.', tech: 'Future expenses = today × (1+inflation)^years. Corpus = PV of inflation-adjusted withdrawals at the real post-retirement return. Projected corpus = current × growth + SIP future value. Results are extremely sensitive to assumptions.', ex: '₹50,000/month today at 6% inflation ≈ ₹2.9 lakh/month in 30 years. EPF: ₹9,600/month at ~8.25% for 25 years ≈ ₹95 lakh (illustrative).', risks: 'Longevity, inflation, healthcare costs, sequence-of-returns risk.', check: ['Use ranges of returns', 'Include EPF/NPS/other income'], mistakes: ['One number for everything', 'Forgetting healthcare inflation'] });
  Q('retirement', mc('What usually happens to the corpus needed if inflation assumption rises?', ['Falls', 'Rises', 'Unchanged', 'Becomes zero'], 1, 'Future expenses are larger.', 'Higher costs need a bigger corpus.', 'retirement'));
  Q('retirement', tf('A single projected corpus number is a guarantee.', false, 'It depends on assumptions; use scenarios.', 'Markets and inflation vary.', 'retirement'));

  /* ---------------- Tax ---------------- */
  L('tax', 'Income tax basics (India)', { analogy: 'Section 80C is a government discount coupon: spend in approved ways and reduce taxable income.', simple: 'You choose the new or old regime each year. Interest and gains are taxed; TDS is just advance tax.', tech: 'Taxable income = income − deductions. Tax by slabs plus cess; rebate for lower incomes. Capital gains depend on asset and holding period. Rules live in year-wise configuration here so they can be updated.', ex: 'Someone in the 30% slab who fully uses ₹1.5 lakh under 80C (old regime) saves ₹45,000 in tax that year, plus the underlying investment\'s return.', risks: 'Wrong regime choice, missing TDS credits, late filing penalties.', check: ['Regime comparison every year', 'Form 26AS / AIS', 'Capital-gains schedule'], mistakes: ['Investing solely for tax saving', 'Ignoring tax on FD interest'] });
  L('tax', 'FD interest is taxed — the real-return check', { analogy: 'Your bonus arrives, but a slice goes to tax before you spend it.', simple: 'Interest is added to income and taxed at your slab.', tech: 'Post-tax return = rate × (1 − slab). Compare with inflation for real return.', ex: '7.5% at a 30% slab ≈ 5.25% post-tax; after 6% inflation that is negative in real terms.', risks: 'TDS at 10% may be lower than your slab — remaining tax due at filing.', check: ['Slab rate', 'TDS threshold'], mistakes: ['Comparing pre-tax FD rate with tax-free options'] });
  Q('tax', mc('What is TDS?', ['A tax-saving scheme', 'Tax deducted at source — an advance tax', 'A penalty', 'A bank fee'], 1, 'The payer deducts tax; you reconcile at filing.', 'It is not a scheme or penalty.', 'incometax'));
  Q('tax', tf('Tax rules are permanent and never change.', false, 'They change with every Budget, which is why they are year-wise configuration.', 'Always verify for the applicable year.', 'incometax'));

  /* ---------------- Property ---------------- */
  L('property', 'Rent vs buy and the full cost of a home', { analogy: 'Buying a house is a long marriage with a bank, a building, and a city.', simple: 'Buying costs more than EMIs: stamp duty, registration, brokerage, interiors, maintenance, property tax, and the opportunity cost of the down payment.', tech: 'Compare net positions: buyer = value − loan − selling costs; renter = down payment + monthly savings invested. Outcomes swing with appreciation, rent growth and investment return. Non-financial factors matter.', ex: '₹60 lakh home with 7% charges adds ≈ ₹4.2 lakh before you own anything. EMI should also be tested at a rate +2%.', risks: 'Rate rise, illiquidity, delays, price stagnation.', check: ['RERA and title', 'EMI as % of income', 'Exit cost'], mistakes: ['Ignoring maintenance and interiors', 'Stretching EMI to the maximum'] });
  Q('property', mc('Which is NOT part of the total cost of buying a home?', ['Stamp duty', 'Registration', 'Brokerage', 'Only the EMI'], 3, '“Only the EMI” ignores charges, maintenance and tax.', 'The other three are upfront costs.', 'rentbuy'));
  Q('property', tf('Rent vs buy results depend heavily on assumptions.', true, 'Appreciation, rent growth and alternate returns can flip the outcome.', 'There is no universal winner.', 'rentbuy'));

  /* ---------------- Vehicle ---------------- */
  L('vehicle', 'The true cost of a vehicle', { analogy: 'A vehicle is a money-leaking bucket: the price is only the first hole.', simple: 'Add EMI, fuel, insurance, service, parking and depreciation.', tech: 'Monthly cost = EMI + fuel + (insurance+service)/12 + parking + depreciation/12. Cost per km = monthly cost ÷ km.', ex: '₹9 lakh car, ₹1.8 lakh down, 9.5% for 5 years: EMI ≈ ₹15,100; fuel at 800 km/month ≈ ₹5,300; insurance and service ≈ ₹4,000; depreciation ≈ ₹9,000 — well over ₹30,000/month.', risks: 'Rapid depreciation, EMI stress, fuel inflation.', check: ['Usage per month', 'Alternatives', 'Resale value'], mistakes: ['Ignoring depreciation because no cash leaves'] });
  Q('vehicle', mc('Which cost appears in the vehicle calculator even though no cash leaves your account?', ['Fuel', 'Depreciation', 'Insurance', 'EMI'], 1, 'Loss of resale value is a real cost.', 'The others are cash payments.', 'car'));
  Q('vehicle', tf('Cost per km helps compare a car with cab or public transport.', true, 'Divide total monthly cost by kilometres.', 'Make sure to include depreciation.', 'car'));

  /* ---------------- Education / marriage / children ---------------- */
  L('education', 'Education costs rise faster than you think', { analogy: 'Planning tuition is chasing a bus that speeds up.', simple: 'Future cost = today\'s cost × (1+education inflation)^years.', tech: 'Education inflation is often higher than general inflation. Required SIP = (future cost − FV of savings) ÷ SIP factor.', ex: '₹20 lakh course today at 8% in 8 years ≈ ₹37 lakh.', risks: 'Return shortfall near the deadline; shift to safer assets as it approaches.', check: ['Scholarships', 'Loan vs savings'], mistakes: ['Using general inflation only'] });
  Q('education', calc('₹10 lakh cost, 10% inflation, 2 years. Future cost (₹)?', 1210000, 100, '10,00,000 × 1.1² = 12,10,000.', 'edu'));
  Q('education', tf('Equity near the deadline carries deadline risk.', true, 'A fall right before fees are due is painful.', 'Shift gradually to safer assets.', 'edu'));
  L('marriage', 'Modelling family events without judgement', { analogy: 'A budget for a big day is a plan for peace of mind.', simple: 'Decide the budget first; calculate backwards.', tech: 'Use the same future-cost model. Also consider family emergency fund, dependants, insurance, children\'s education.', ex: '₹15 lakh today, 4 years, 7% → ≈ ₹19.7 lakh.', risks: 'Borrowing for events adds interest.', check: ['Total cost', 'Who contributes'], mistakes: ['Counting gifts as certain income'] });
  Q('marriage', mc('Which should come first when planning a big family event?', ['Loan', 'A target budget and a monthly contribution', 'Credit card', 'Nothing'], 1, 'Plan backwards from the number.', 'Borrowing adds interest.', 'marriage'));
  Q('marriage', tf('The calculator tells you how to celebrate.', false, 'It only models numbers; the choices are yours.', 'No prescriptions.', 'marriage'));
  L('children', 'Planning for a child', { analogy: 'Planning for a child is planting a tree: the earlier, the smaller the daily effort.', simple: 'Education costs, health cover, term cover and a family emergency fund matter.', tech: 'Years to need = education age − child\'s age. SSY (for girls) and PPF are options; equity SIPs suit longer horizons, shifting to safer assets later.', ex: '₹25 lakh today, age 2 → 18, 8% inflation → ≈ ₹86 lakh in 16 years.', risks: 'Underestimating costs, no insurance.', check: ['Term + health first', 'Review yearly'], mistakes: ['Mixing insurance and investment plans'] });
  Q('children', calc('Years until needed if the child is 3 and education starts at 18?', 15, 0, '18 − 3 = 15.', 'child'));
  Q('children', tf('A term plan is pure protection with no maturity value.', true, 'That is why it is cheap.', 'Combined plans cost more for less cover.', 'cover'));

  /* ---------------- Crypto ---------------- */
  L('crypto', 'Bitcoin and crypto: education, not a tip', { analogy: 'Betting on a very fast, unpredictable horse: legal, but never with your rent money.', simple: 'Crypto are digital assets whose prices swing a lot. Bitcoin runs on a blockchain, a shared ledger.', tech: 'Private key = control; lose it and funds are gone. Custody: exchange vs self. Volatility: 80%+ drawdowns have occurred. India: flat tax on gains, no loss set-off and TDS on transfers under current rules — verify. Regulation can change.', ex: '₹1 lakh doubles → ₹30,000 tax, leaving ₹1.7 lakh; if it halves, the ₹50,000 loss cannot offset other income (current rules).', risks: 'Total loss, exchange failure, fake coins, taxes, fraud.', check: ['Could I lose 100%?', 'Platform verification', 'Position size', 'Tax & TDS'], mistakes: ['Buying on celebrity endorsement', 'Using borrowed money'] });
  L('crypto', 'Crypto safety: wallets, keys and fraud', { analogy: 'A private key is the only key to a vault that nobody else can open — even for you if lost.', simple: 'Never share seed phrases. Prefer verified platforms. Avoid guaranteed-return “staking”.', tech: 'Hot vs cold wallets; 2FA; address whitelisting; phishing of seed phrases; rug-pulls.', ex: 'A “high-yield staking app” promising 1% a day is a textbook Ponzi pattern.', risks: 'Irreversible transactions.', check: ['Official domains', 'Withdrawal test'], mistakes: ['Storing seed phrase in email/cloud'] });
  Q('crypto', mc('Which is the clearest crypto red flag?', ['Clear risk disclosures', 'Guaranteed daily returns', 'A published tax note', 'Verified exchange'], 1, 'Guaranteed returns are the Ponzi signature.', 'The others are normal.', 'cryptoscen'));
  Q('crypto', tf('Scenario tables (e.g. +100% to −100%) are predictions.', false, 'They illustrate outcomes, not forecasts.', 'Nobody can predict prices.', 'cryptoscen'));

  /* ---------------- Business ---------------- */
  L('business', 'Business finance basics', { analogy: 'A business is a bucket with a hole (costs) and a tap (revenue); break-even is when the tap matches the leak.', simple: 'Revenue − costs = profit. Cash flow timing can sink a profitable business.', tech: 'Gross profit = revenue − direct cost. Operating profit = gross − operating expenses. Break-even units = fixed costs ÷ (price − variable cost). Runway = cash ÷ net burn. Start lean: Udyam registration (free), GST by turnover thresholds (verify), Mudra/CGTMSE for collateral-free credit (verify limits). Structure: proprietorship, partnership, LLP, OPC, Pvt Ltd.', ex: 'Fixed ₹1 lakh/month, price ₹100, variable ₹60 → margin ₹40 → break-even 2,500 units/month.', risks: 'Cash gaps, personal liability, revenue below plan.', check: ['12 months personal runway', 'Break-even time', 'Compliance'], mistakes: ['Mixing personal and business money', 'Registering too late'] });
  Q('business', calc('Fixed costs ₹1,00,000; price ₹100; variable cost ₹60. Break-even units?', 2500, 0, '1,00,000 ÷ 40 = 2,500.', 'breakeven'));
  Q('business', mc('Runway is…', ['Revenue growth', 'Cash ÷ monthly net burn', 'Profit margin', 'Tax rate'], 1, 'Months until cash runs out.', 'Others are different measures.', 'runway'));

  /* ---------------- FI ---------------- */
  L('fi', 'Financial independence', { analogy: 'FI is building a stream that pays your bills so work becomes a choice.', simple: 'Reach a corpus whose sustainable withdrawals cover expenses.', tech: 'FI number = annual expenses ÷ withdrawal rate. A 3–4% rate is a rule of thumb, not a guarantee. Savings rate and returns both matter; inflation grows the target.', ex: '₹50,000/month = ₹6 lakh/year ÷ 3.5% ≈ ₹1.7 crore today.', risks: 'Sequence risk, healthcare, inflation.', check: ['Scenarios across returns', 'Healthcare cover'], mistakes: ['Ignoring taxes on withdrawals'] });
  Q('fi', calc('Annual expenses ₹6,00,000; withdrawal rate 4%. FI number (₹)?', 15000000, 1, '6,00,000 ÷ 0.04 = 1,50,00,000.', 'fi'));
  Q('fi', tf('A 4% rule guarantees your money will last.', false, 'It is a rule of thumb, not a guarantee.', 'Depends on market sequence and inflation.', 'fi'));

  /* ---------------- Net worth / goals / scenarios / oppcost / decision / health ---------------- */
  L('networth', 'Net worth: your financial scoreboard', { analogy: 'Net worth is your personal balance sheet.', simple: 'Own minus owe.', tech: 'Net worth = assets − liabilities. Track monthly snapshots. Use realistic resale values for vehicles and property.', ex: '₹3 lakh assets − ₹1 lakh liabilities = ₹2 lakh.', risks: 'Overstating illiquid assets.', check: ['Values updated', 'Nominees'], mistakes: ['Counting what you cannot sell'] });
  Q('networth', calc('Assets ₹3,00,000; liabilities ₹1,00,000. Net worth (₹)?', 200000, 0, '3,00,000 − 1,00,000.', 'networthcalc'));
  Q('networth', tf('Net worth includes both assets and loans.', true, 'Assets minus liabilities.', 'Ignoring loans overstates wealth.', 'networthcalc'));
  L('goals', 'Goals need numbers', { analogy: 'A goal without a number is a wish.', simple: 'Target, deadline, assumptions → monthly amount.', tech: 'Required monthly = (future target − FV of current) ÷ SIP factor. Short goals: low volatility; long goals can take more.', ex: '₹1 lakh laptop in 2 years at 5% inflation ≈ ₹1.1 lakh → about ₹4,300/month at 6%.', risks: 'Inflation, unrealistic returns.', check: ['Deadline flexibility'], mistakes: ['Using equity for 1-year goals'] });
  Q('goals', mc('Why inflate the target amount?', ['To scare', 'Because the price at the deadline will probably be higher', 'It is required by law', 'It lowers monthly savings'], 1, 'Costs rise.', 'Ignoring inflation under-saves.', 'goal'));
  Q('goals', tf('Short-term goals usually suit low-volatility assets.', true, 'A fall near the deadline cannot be waited out.', 'Equity suits long horizons.', 'goal'));
  L('scenarios', 'Scenarios, not predictions', { analogy: 'A flight simulator: practise storms safely.', simple: 'Change one assumption; see the effect.', tech: 'Deterministic simulations with user inputs. Use low/base/high; never a single future.', ex: 'Inflation 8% vs 6% changes retirement corpus by lakhs.', risks: 'False precision.', check: ['Assumptions listed'], mistakes: ['Trusting a single projection'] });
  Q('scenarios', mc('What is a scenario?', ['A prediction', 'A what-if under stated assumptions', 'A guarantee', 'A rumour'], 1, 'It explores outcomes given assumptions.', 'It never predicts.', 'whatif-invest'));
  Q('scenarios', tf('Scenario results should be shown as ranges.', true, 'Uncertainty is real.', 'Single numbers mislead.', 'whatif-invest'));
  L('oppcost', 'Opportunity cost', { analogy: 'Choosing a movie means not seeing the other one — and not saving the ticket money.', simple: 'What else could the same money do?', tech: 'Compare spending, saving as cash and investing under hypothetical returns, with taxes/fees/inflation ignored unless modelled.', ex: '₹50,000 at 0%, 7%, 12% for 10 years = ₹50,000; ≈ ₹98,000; ≈ ₹1.55 lakh.', risks: 'Returns can be negative.', check: ['Horizon', 'Risk'], mistakes: ['Thinking opportunity cost is a loss you must avoid at any price'] });
  Q('oppcost', calc('₹50,000 at 10% for 1 year (₹)?', 55000, 1, '50,000 × 1.1 = 55,000.', 'oppcost'));
  Q('oppcost', tf('Opportunity cost illustrations are guaranteed.', false, 'They are hypothetical.', 'Clearly labelled.', 'oppcost'));
  L('decision', 'A decision framework', { analogy: 'A pilot\'s checklist: you still fly the plane, but you do not skip steps.', simple: 'Ask: what is it, why, total cost, fees, tax, alternatives, risks, worst case.', tech: 'Learn → calculate → compare → check risks → taxes/fees → opportunity cost → long-term impact → decide.', ex: 'A ₹70,000 phone on no-cost EMI: compare with cash price and alternatives.', risks: 'Urgency and social pressure.', check: ['Wait 72 hours'], mistakes: ['Deciding when emotional'] });
  Q('decision', mc('What does the Decision Engine tell you to do?', ['Buy', 'Not buy', 'It shows facts and questions; you decide', 'Borrow'], 2, 'It never gives yes/no.', 'The decision is yours.', 'oppcost'));
  Q('decision', tf('Fake urgency is a reason to decide quickly.', false, 'Urgency is a pressure tactic.', 'Take time to verify.', 'oppcost'));
  L('health', 'Reading your financial health', { analogy: 'Health check-ups show separate vitals, not one mystery number.', simple: 'Look at emergency fund, savings rate, debt, insurance, investing, goals, net worth and cash flow separately.', tech: 'Each metric has a formula, a reference band, and limitations.', ex: 'DTI 30% is “watch”, not “failure”.', risks: 'Benchmarks differ per person.', check: ['Trend over months'], mistakes: ['Chasing a score'] });
  Q('health', mc('Why not use a single secret score?', ['Scores are illegal', 'A mysterious score hides the methodology', 'It costs money', 'Nobody wants it'], 1, 'Transparency matters.', 'Each metric here is explained.', 'dti'));
  Q('health', tf('Benchmarks are rules of thumb.', true, 'They don’t fit everyone.', 'Context matters.', 'dti'));

  /* ---------------- Learning path (journey) ---------------- */
  const JOURNEY = [['₹50 vegetable purchase', 'spending'], ['₹200 coffee', 'spending'], ['₹1,000 subscription', 'spending'], ['₹10,000 monthly expenses', 'budgeting'], ['First salary', 'income'], ['Bank account', 'banking'], ['Emergency fund', 'emergency'], ['Credit card', 'cards'], ['Loan', 'loans'], ['Insurance', 'insurance'], ['Investments', 'investing'], ['Tax', 'tax'], ['Vehicle', 'vehicle'], ['House', 'property'], ['Marriage / family', 'marriage'], ['Children\'s education', 'children'], ['Retirement', 'retirement'], ['Financial independence', 'fi'], ['Wealth preservation', 'networth'], ['Advanced investing', 'crypto']];

  const EDUCATIONAL_CONTENT = { lessons: LESSONS, quiz: QUIZ, journey: JOURNEY };
  FOS.LESSONS = LESSONS; FOS.QUIZ = QUIZ; FOS.JOURNEY = JOURNEY; FOS.EDUCATIONAL_CONTENT = EDUCATIONAL_CONTENT;
  window.EDUCATIONAL_CONTENT = EDUCATIONAL_CONTENT;
})();
