/* ==========================================================================
   decision.js — WHAT ARE YOU ABOUT TO DO? + "Things people forget"
   Never says yes/no. Shows facts, costs, risks, alternatives and questions.
   ========================================================================== */
(function () {
  'use strict';
  const C = FOS.calc, fmt = FOS.fmt, U = FOS.ui, esc = U.esc, store2 = () => FOS.store.get();
  const D = (label, kind, o) => Object.assign({ label, kind }, o);
  const DECISIONS = {
    spend: D('Spend Money', 'spend', { what: 'A one-time or occasional purchase.', fee: 'Delivery, convenience fees, taxes on the invoice.', tax: 'GST is normally included in the price; no deduction available for personal spending.', liq: 'Money is gone; only resale value (if any) can come back.', risks: ['Regret or unused item', 'Price drops soon after', 'Weak return / warranty terms'], worst: 'The item fails or you do not use it, and the money cannot be recovered.', alts: ['Wait 72 hours', 'Buy second-hand or a cheaper model', 'Rent or borrow'], exit: 'Resale typically well below the price paid.', verify: ['Is this a need or a want?', 'What is the total cost including extras?', 'What is the return / warranty policy?'] }),
    borrow: D('Borrow Money', 'debt', { what: 'A loan to be repaid with interest.', fee: 'Processing fee, GST, documentation, insurance, part-payment charges.', tax: 'Interest on some loans (home, education) may qualify for deductions — verify.', liq: 'You owe fixed payments regardless of your income.', risks: ['EMI stress if income falls', 'Floating rate can rise', 'Default harms credit score and may put collateral at risk'], worst: 'Income stops and the loan goes into default; collateral may be seized and credit score damaged.', alts: ['Save and pay later', 'Smaller amount / shorter need', 'Cheaper lender, secured instead of unsecured'], exit: 'Foreclosure / prepayment charges may apply.', verify: ['Total repayment and effective rate (APR)?', 'Prepayment and late charges?', 'Is the rate fixed or floating, and when does it reset?', 'EMI as % of income?'], rate: 'personalLoan', ten: 36 }),
    card: D('Use Credit Card', 'debt', { what: 'A short-term, interest-free loan if you pay in full by the due date.', fee: 'Annual fee, late fee, forex mark-up, cash-advance fee, GST.', tax: 'Interest and fees are not deductible.', liq: 'Any unpaid balance attracts interest from the transaction date in many cases.', risks: ['Carrying a balance at ~36–45% a year', 'Overspending because payment is deferred', 'Credit utilization hurts your score'], worst: 'You carry the balance for years paying only the minimum; the interest can exceed the original purchase.', alts: ['Debit card / UPI', 'Save first, pay later', 'Low-cost EMI only if interest is clear'], exit: 'Interest accrues until repaid.', verify: ['Can I pay the FULL bill on the due date?', 'What is the interest if I don\'t?', 'Is autopay set?'], rate: 'creditCardAPR', ten: 12 }),
    insurance: D('Buy Insurance', 'insure', { what: 'A contract that pays in defined situations in exchange for premiums.', fee: 'Premium, GST, add-on riders, possible agent commission built into the premium.', tax: 'Premiums may qualify for deductions under the old regime; claim/maturity taxation varies — verify.', liq: 'Premium is a sunk cost for the cover; some products have surrender charges.', risks: ['Claim rejection due to exclusions / non-disclosure', 'Premium increases at renewal', 'Over- or under-insurance'], worst: 'You claim and discover the event is excluded or the sum insured is far too small.', alts: ['Pure term + separate investing instead of a combined plan', 'Higher deductible', 'Employer cover plus a personal top-up'], exit: 'Early exit often means losing premiums paid or heavy surrender charges.', verify: ['Exclusions and waiting periods?', 'Claim settlement process and network?', 'Renewal and portability terms?', 'Disclosed everything honestly?'] }),
    invest: D('Invest', 'invest', { what: 'Putting money into an asset hoping it grows over time.', fee: 'Expense ratios, brokerage, exit load, platform fees.', tax: 'Interest, dividends and capital gains are taxable; rates depend on the asset and holding period.', liq: 'Varies: savings (high) → equity/MFs (medium-high) → property (low).', risks: ['Market fall', 'Inflation beating returns', 'Fraud / mis-selling', 'Needing the money early'], worst: 'A large fall right when you need the money, or permanent loss.', alts: ['Prepay high-interest debt (a “guaranteed” return)', 'Build the emergency fund first', 'Low-cost index fund / PPF / FD depending on horizon'], exit: 'Selling early may trigger exit load, taxes and selling at a loss.', verify: ['Is my emergency fund and insurance in place?', 'What is my time horizon?', 'Can I stay invested through a 30–50% fall?', 'All fees and taxes?'], ret: 10, ten: 0 }),
    stock: D('Buy Stock', 'invest', { what: 'A share of ownership in one company.', fee: 'Brokerage, STT, exchange charges, DP charges, GST.', tax: 'Short-term and long-term capital gains tax; dividends taxed at slab.', liq: 'High (sell on market days) — but price may be low.', risks: ['Company-specific risk', 'Market fall', 'Tips and rumours', 'Over-concentration'], worst: 'The company fails or falls 70–100%; shares become worthless.', alts: ['Diversified index fund', 'Smaller position', 'Learn to read financial statements first'], exit: 'Market price on the day you sell, less charges and tax.', verify: ['Can I explain how the company earns?', 'What % of my portfolio is this?', 'Where did this idea come from?'], ret: 12 }),
    mf: D('Buy Mutual Fund', 'invest', { what: 'A pooled fund managed by an AMC.', fee: 'Expense ratio (direct vs regular), exit load, stamp duty on purchase.', tax: 'Depends on category (equity/debt) and holding period.', liq: 'High — redemption in a few working days.', risks: ['NAV fluctuations', 'Fund-manager / strategy risk', 'Credit risk in debt funds'], worst: 'NAV drops deeply near your goal date.', alts: ['Index fund / ETF', 'FD/RD for short goals', 'Direct vs regular plan'], exit: 'Exit load and taxes may apply.', verify: ['Category and riskometer?', 'Expense ratio difference direct vs regular?', 'Exit load period?'], ret: 11 }),
    gold: D('Buy Gold', 'invest', { what: 'Gold as jewellery, coin, ETF, digital gold or sovereign bond.', fee: 'Making charges, GST, storage, expense ratio, buy-sell spread.', tax: 'Capital gains rules depend on form and holding period.', liq: 'Jewellery: medium (with deduction); ETF: high.', risks: ['Price can stay flat for years', 'Purity / theft risk', 'High making charges'], worst: 'You pay 10–20% in charges on jewellery and prices do not rise.', alts: ['Gold ETF/fund', 'Sovereign gold bonds where available', 'Smaller allocation'], exit: 'Buy-back deductions on jewellery can be 5–25%.', verify: ['Making + GST total?', 'Buy-back price vs buy price?', 'Hallmark / purity?'], ret: 7 }),
    crypto: D('Buy Crypto', 'invest', { what: 'A digital asset such as Bitcoin, priced by trading.', fee: 'Exchange fees, spread, withdrawal and network fees, TDS.', tax: 'Flat tax on gains, no set-off for losses, TDS on transfers (verify current rules).', liq: 'High on exchanges — but prices can gap.', risks: ['80%+ drawdowns', 'Exchange failure / hacks', 'Scams and fake coins', 'Regulatory change'], worst: 'Total loss, and you still cannot offset the loss against other income.', alts: ['Do nothing', 'Small amount you can lose completely', 'Diversified assets'], exit: 'Spread + fees + tax + TDS.', verify: ['Could I lose 100% and be fine?', 'Who holds the private keys?', 'Is anyone promising returns?'], ret: 0 }),
    vehicle: D('Buy Vehicle', 'asset', { what: 'A vehicle used for transport.', fee: 'Registration, road tax, insurance, accessories, loan processing.', tax: 'Road tax/GST included in on-road price; business use may differ.', liq: 'Low — resale value drops quickly in the first years.', risks: ['Depreciation', 'Fuel and maintenance inflation', 'EMI burden'], worst: 'Income falls while EMI continues and the resale value is below the loan outstanding.', alts: ['Used vehicle', 'Cab / rental', 'Public transport'], exit: 'Resale at well below price; foreclosure charges.', verify: ['Monthly + annual + cost per km?', 'EMI as % of income?', 'Resale value after 5 years?'], rate: 'carLoan', ten: 60, rec: 10000 }),
    house: D('Buy House', 'asset', { what: 'Residential property for use or investment.', fee: 'Stamp duty, registration, brokerage, loan fees, interiors, society deposits.', tax: 'Interest deductions, capital gains on sale, property tax.', liq: 'Very low — sale can take months.', risks: ['Rate rises on floating loans', 'Price stagnation', 'Delays / title issues', 'Job relocation'], worst: 'Prices fall or stay flat while EMI continues; selling costs are high.', alts: ['Rent and invest the difference', 'Smaller/cheaper home', 'Delay to raise a bigger down payment'], exit: 'Brokerage, taxes, waiting time, price concession.', verify: ['Total cost including all charges?', 'EMI if rate +2%?', 'RERA, title, approvals?'], rate: 'homeLoan', ten: 240, rec: 5000 }),
    eduloan: D('Take Education Loan', 'debt', { what: 'Loan to fund a course, repaid after/while studying.', fee: 'Processing, insurance, moratorium interest.', tax: 'Interest may qualify for a deduction — verify.', liq: 'Repayment starts after the moratorium regardless of job outcome.', risks: ['Lower-than-expected salary', 'Course or visa problems', 'Interest accrual during study'], worst: 'Course outcome does not lead to expected income; repayment burden remains.', alts: ['Scholarships', 'Cheaper course / location', 'Part-time income'], exit: 'Prepayment allowed usually with no charge for individuals — verify.', verify: ['Expected salary vs EMI?', 'Interest during moratorium?', 'Collateral and co-borrower liability?'], rate: 'educationLoan', ten: 84 }),
    business: D('Start Business', 'asset', { what: 'Starting or investing in your own venture.', fee: 'Registrations, licences, legal/CA fees, setup.', tax: 'Business income taxed; GST applicability by turnover.', liq: 'Very low — capital is tied up.', risks: ['Revenue below plan', 'Cash-flow gaps', 'Personal liability', 'Time and opportunity cost'], worst: 'Business closes; capital and personal savings are lost, plus any personal guarantees.', alts: ['Start part-time', 'Validate with small orders', 'Freelance first'], exit: 'Winding down costs and unsold inventory.', verify: ['Break-even units and runway in months?', 'Personal runway for 12 months?', 'Registrations and compliance?'], ret: 0 }),
    subscribe: D('Subscribe', 'spend', { what: 'A recurring charge for a service.', fee: 'Auto-renewal price rises, taxes, cancellation terms.', tax: 'No deduction for personal use.', liq: 'Money is spent each cycle.', risks: ['Forgotten renewals', 'Price increases', 'Free-trial conversion'], worst: 'You pay for years for something unused.', alts: ['Share plans where allowed', 'Pause/cancel after use', 'Annual plan only if truly used'], exit: 'Cancellation may forfeit the period paid.', verify: ['Annual cost?', 'How do I cancel?', 'When does the free trial end?'], rec: 500 }),
    travel: D('Travel', 'spend', { what: 'A trip with transport, stay and activities.', fee: 'Booking fees, forex, visa, insurance, baggage.', tax: 'TCS may apply on overseas packages — verify.', liq: 'Non-refundable bookings are lost if plans change.', risks: ['Cancellations', 'Medical costs abroad', 'Currency moves'], worst: 'Trip cancelled, non-refundable; or an emergency abroad without insurance.', alts: ['Nearer destination', 'Off-season', 'Travel later and save first'], exit: 'Cancellation charges.', verify: ['Refund policy?', 'Travel insurance?', 'All-in cost incl. incidentals?'] })
  };
  FOS.DECISIONS = DECISIONS;

  const FORGET = ['TOTAL COST', 'RECURRING COST', 'INTEREST', 'FEES', 'TAX', 'INFLATION', 'LIQUIDITY', 'RISK', 'OPPORTUNITY COST', 'EXIT COST', 'WORST CASE', 'ALTERNATIVES', 'LONG-TERM IMPACT'];
  FOS.forgetItems = function (d) {
    d = typeof d === 'string' ? DECISIONS[d] || DECISIONS.spend : d;
    return [
      ['TOTAL COST', 'Price + fees + interest + running costs over the whole holding period — not the sticker price.'],
      ['RECURRING COST', d.kind === 'asset' ? 'Maintenance, insurance, fuel, society charges, taxes — every month and every year.' : 'Subscriptions, renewals, top-ups and upgrades that follow the first payment.'],
      ['INTEREST', d.kind === 'debt' || d.rate ? 'Reducing-balance interest adds up to a large share of the price; check the APR, not only the EMI.' : 'If you finance it, interest applies. If you hold it instead of investing, interest is what you give up.'],
      ['FEES', d.fee],
      ['TAX', d.tax],
      ['INFLATION', 'In ten years at ~6%, today\'s ₹1,00,000 buys what ≈₹56,000 buys now. Returns must beat this to grow real wealth.'],
      ['LIQUIDITY', d.liq],
      ['RISK', d.risks.join(' · ')],
      ['OPPORTUNITY COST', 'The same money could do something else: pay off debt, build an emergency fund, or be invested under hypothetical assumptions.'],
      ['EXIT COST', d.exit],
      ['WORST CASE', d.worst],
      ['ALTERNATIVES', d.alts.join(' · ')],
      ['LONG-TERM IMPACT', 'How does this change your monthly cash flow, savings rate and net worth 5, 10, 20 years from now?']
    ];
  };

  FOS.forgetHTML = (id) => `<div class="forget">${FOS.forgetItems(id).map(([t, x]) => `<div class="forget-item"><h5>${esc(t)}</h5><p>${esc(x)}</p></div>`).join('')}</div>`;

  FOS.tools.decision = function (root) {
    const m = FOS.metrics();
    root.innerHTML = `<div class="card"><h3>WHAT ARE YOU ABOUT TO DO?</h3><p class="muted">Choose an action. You will get the questions people forget to ask, with numbers calculated from what you enter. You get a clear verdict at the end, with the numbers behind it.</p>
      <div class="chips" role="radiogroup" aria-label="Action">${Object.entries(DECISIONS).map(([k, d], i) => `<button class="chip ${i === 0 ? 'on' : ''}" role="radio" aria-checked="${i === 0}" data-d="${k}">${esc(d.label)}</button>`).join('')}</div></div><div id="dform"></div><div id="dout"></div>`;
    let cur = 'spend';
    const form = root.querySelector('#dform'), out = root.querySelector('#dout');
    const buildForm = () => {
      const d = DECISIONS[cur], rate = d.rate ? FOS.store.interest(d.rate) : 0;
      form.innerHTML = `<div class="card"><h4>${esc(d.label)} — tell me the numbers</h4><div class="fields">
        <div class="field wide"><label>WHAT IS IT?<input class="input" id="d-what" maxlength="80" placeholder="${esc(d.what)}"></label></div>
        <div class="field wide"><label>WHY DO YOU NEED IT?<input class="input" id="d-why" maxlength="120" placeholder="Need, want, goal…"></label></div>
        <div class="field"><label>Amount (₹)<input class="input" id="d-amt" type="number" min="0" step="any" value="${d.kind === 'spend' ? 20000 : 500000}"></label></div>
        <div class="field"><label>Recurring cost per month (₹)<input class="input" id="d-rec" type="number" min="0" step="any" value="${d.rec || 0}"></label></div>
        <div class="field"><label>Fees & charges (₹)<input class="input" id="d-fee" type="number" min="0" step="any" value="0"></label></div>
        <div class="field"><label>Taxes payable (₹)<input class="input" id="d-tax" type="number" min="0" step="any" value="0"></label></div>
        <div class="field"><label>Financed by loan? (0 = no, else interest % p.a.)<input class="input" id="d-rate" type="number" min="0" step="0.1" value="${d.kind === 'debt' || d.ten ? rate : 0}"></label></div>
        <div class="field"><label>Loan tenure (months)<input class="input" id="d-ten" type="number" min="0" step="1" value="${d.ten || 0}"></label></div>
        <div class="field"><label>Holding period (years)<input class="input" id="d-yrs" type="number" min="1" step="1" value="10"></label></div>
        <div class="field"><label>Hypothetical alternative return %<input class="input" id="d-alt" type="number" min="0" max="30" step="0.5" value="10"></label></div>
        <div class="field"><label>If income falls by (%)<input class="input" id="d-inc" type="number" min="0" max="100" value="30"></label></div>
        <div class="field"><label>If price rises by (%)<input class="input" id="d-pr" type="number" min="0" max="100" value="10"></label></div>
        <div class="field"><label>Cost of exiting early (% of amount)<input class="input" id="d-exit" type="number" min="0" max="100" step="0.5" value="${d.kind === 'spend' ? 60 : d.kind === 'invest' ? 3 : 15}"></label></div>
      </div></div>`;
      run();
    };
    const run = () => {
      const d = DECISIONS[cur], g = (id) => Math.max(0, parseFloat(form.querySelector('#' + id).value) || 0), txt = (id) => form.querySelector('#' + id).value;
      if (U.looksSensitive(txt('d-what') + txt('d-why'))) { out.innerHTML = `<div class="card"><p class="warn-t">${U.SENSITIVE_MSG}</p></div>`; return; }
      const amt = g('d-amt'), rec = g('d-rec'), fee = g('d-fee'), tax = g('d-tax'), rate = g('d-rate'), ten = Math.round(g('d-ten')), yrs = Math.max(1, g('d-yrs')), alt = g('d-alt'), finance = rate > 0 && ten > 0;
      const emi = finance ? C.emi(amt, rate, ten) : 0, interest = finance ? emi * ten - amt : 0, total = amt + fee + tax + interest + rec * 12 * yrs;
      const upfront = finance ? 0 : amt + fee + tax, oppLump = upfront, oppFV = C.fv(oppLump, alt, yrs) + C.sipFV(rec, alt, yrs * 12) + (finance ? C.sipFV(emi, alt, Math.min(ten, yrs * 12)) * Math.pow(1 + alt / 100, Math.max(0, yrs - ten / 12)) : 0);
      const fall = g('d-inc') / 100, newInc = m.income * (1 - fall), monthlyLoad = emi + rec, surplus = newInc - m.expenses - monthlyLoad;
      const jobBurn = m.essential + m.emi + monthlyLoad, afterSav = Math.max(0, m.liquid - upfront - fee - tax), jobMonths = jobBurn > 0 ? afterSav / jobBurn : NaN;
      const ex = g('d-exit') / 100, priceUp = g('d-pr') / 100, rows = FOS.forgetItems(d), riskLevel = { spend: 'Low–moderate (regret / waste)', debt: 'Moderate–high (fixed obligations)', insure: 'Low (financial), but coverage risk', invest: 'Market-dependent — can be high', asset: 'Moderate–high (illiquid, large, long)' }[d.kind];
      const noProfile = m.income <= 0 ? '<p class="note">Add your income and expenses (Budget or Onboarding) to personalise the income and job-loss answers.</p>' : '';
      const outlay = upfront + fee + tax, loadPct = m.income > 0 ? (emi + rec) / m.income * 100 : NaN, dtiAfter = m.income > 0 ? (m.emi + emi) / m.income * 100 : NaN, burn0 = m.essential + m.emi, efAfterM = burn0 > 0 ? (m.liquid - outlay) / burn0 : NaN;
      const cc = store2().liabilities.filter((l) => l.cat === 'Credit card' && +l.value > 0).reduce((a, l) => a + +l.value, 0), checks = [], fixes = [];
      const vchk = (okk, good, bad, fix) => { checks.push([okk, okk ? good : bad]); if (!okk && fix) fixes.push(fix); };
      if (m.income > 0) {
        if (d.kind === 'spend' || d.kind === 'asset' || d.kind === 'debt') vchk(loadPct <= (d.kind === 'spend' ? 5 : 15), `Monthly commitment is ${fmt.pct(loadPct, 1)} of income`, `Monthly commitment is ${fmt.pct(loadPct, 1)} of income — above the ${d.kind === 'spend' ? 5 : 15}% comfort level`, loadPct > 0 && rate > 0 && ten > 0 ? `Lower the amount to about ${fmt.inr(Math.max(0, (((d.kind === 'spend' ? 5 : 15) / 100 * m.income - rec) / C.emi(1, rate, ten))))} or extend/reduce the recurring cost` : 'Reduce the recurring cost');
        if (finance || d.kind === 'debt') vchk(dtiAfter <= 40, `All EMIs would be ${fmt.pct(dtiAfter, 0)} of take-home (limit ~40%)`, `All EMIs would be ${fmt.pct(dtiAfter, 0)} of take-home — over the ~40% limit`, `Keep total EMIs within ${fmt.inr(0.4 * m.income)}: your room for a new EMI is ${fmt.inr(Math.max(0, 0.4 * m.income - m.emi))}`);
        vchk(efAfterM >= 3, `After paying, cash still covers ${Number.isFinite(efAfterM) ? efAfterM.toFixed(1) : '—'} months (6 is the target)`, `After paying, cash covers only ${Number.isFinite(efAfterM) ? Math.max(0, efAfterM).toFixed(1) : '0'} months — below the 3-month floor`, `Keep at least ${fmt.inr(3 * burn0)} in cash: the most you can pay out now is ${fmt.inr(Math.max(0, m.liquid - 3 * burn0))}`);
        vchk(surplus >= 0, `Still cash-positive if income falls ${fmt.pct(fall * 100, 0)}`, `If income falls ${fmt.pct(fall * 100, 0)} you would be short by ${fmt.inr(-surplus)} a month`, 'Reduce the monthly commitment, or build a bigger buffer before committing');
        if (d.kind === 'invest' && cc > 0) vchk(false, '', `You owe ${fmt.inr(cc)} on credit cards — clearing it earns a guaranteed ${FOS.store.interest('creditCardAPR')}% that no investment matches`, 'Clear the card balance first, then invest');
        if (d.kind === 'invest' && !store2().profile.hasHealth) vchk(false, '', 'No health insurance recorded — one hospital bill could force you to sell this investment at a loss', 'Buy health cover first');
        if (d.kind === 'invest' && Number.isFinite(m.efMonths) && m.efMonths < 3) vchk(false, '', `Emergency fund is ${m.efMonths.toFixed(1)} months — build it before taking market risk`, 'Fund 3–6 months of expenses first');
      }
      const failN = checks.filter((c2) => !c2[0]).length, hardFail = checks.some((c2) => !c2[0] && /below the 3-month|short by|over the ~40%|credit cards|emergency fund is/.test(c2[1]));
      const vcls = !checks.length ? '' : failN === 0 ? 'go' : hardFail ? 'hold' : 'change', vtxt = !checks.length ? 'Add your income and savings (Budget / onboarding) to get a verdict' : failN === 0 ? 'GO AHEAD — it fits your numbers' : hardFail ? 'HOLD OFF FOR NOW — fix the items below first' : 'POSSIBLE WITH CHANGES — adjust the items below';
      const adviser = `<div class="card verdict ${vcls}"><h3>ADVISER VERDICT: ${esc(vtxt)}</h3>${checks.length ? `<ul class="vlist">${checks.map((c2) => `<li>${c2[0] ? '✅' : '⚠️'} ${esc(c2[1])}</li>`).join('')}</ul>${fixes.length ? `<h4>To make it work</h4><ul>${fixes.map((f) => `<li>${esc(f)}</li>`).join('')}</ul>` : ''}` : ''}<p class="note">Based on your recorded income, EMIs and savings and the standard comfort limits (commitment ≲ 15% of income, EMIs ≤ 40%, 3+ months of cash left). Change the numbers above to test alternatives.</p></div>`;
      const A = (q, body) => `<div class="qa"><h5>${q}</h5><div>${body}</div></div>`;
      out.innerHTML = `<div class="card"><h3>Questions to answer before you decide</h3>
        ${A('WHAT IS IT?', esc(txt('d-what') || d.what))}${A('WHY DO YOU NEED IT?', esc(txt('d-why') || 'Write down your reason — if you cannot, pause.'))}
        ${A('WHAT IS THE TOTAL COST?', `<b>${fmt.inr(total)}</b> over ${yrs} years = price ${fmt.inr(amt)} + fees ${fmt.inr(fee)} + taxes ${fmt.inr(tax)} + interest ${fmt.inr(interest)} + recurring ${fmt.inr(rec * 12 * yrs)}.${finance ? ` EMI ${fmt.inr(emi)} × ${ten}.` : ''}`)}
        ${A('WHAT ARE THE FEES?', `${esc(d.fee)}<br>You entered: <b>${fmt.inr(fee)}</b>.`)}
        ${A('WHAT ARE THE TAXES?', `${esc(d.tax)}<br>You entered: <b>${fmt.inr(tax)}</b>. Verify current rules.`)}
        ${A('WHAT IS THE OPPORTUNITY COST?', upfront > 0 || rec > 0 ? `Instead, ${fmt.inr(upfront)}${rec ? ' plus ' + fmt.inr(rec) + '/month' : ''} at a hypothetical <b>${alt}%</b> could be ≈ <b>${fmt.inr(oppFV)}</b> in ${yrs} years. <em>Illustrative, not guaranteed.</em>` : 'Enter an amount to calculate.')}
        ${A('WHAT ARE THE RISKS?', `<ul>${d.risks.map((r) => `<li>${esc(r)}</li>`).join('')}</ul>`)}
        ${A('WHAT IS THE WORST-CASE SCENARIO?', esc(d.worst) + (d.kind === 'invest' && m.netWorth > 0 ? `<br>If this amount went to zero it would be <b>${fmt.pct(amt / m.netWorth * 100, 1)}</b> of your net worth.` : ''))}
        ${A('WHAT ARE THE ALTERNATIVES?', `<ul>${d.alts.map((r) => `<li>${esc(r)}</li>`).join('')}</ul>`)}
        ${A('WHAT HAPPENS IF YOUR INCOME FALLS?', m.income > 0 ? `If income falls ${fmt.pct(fall * 100, 0)} to ${fmt.inr(newInc)}, with this added load of ${fmt.inr(monthlyLoad)}/month your monthly surplus becomes <b class="${surplus < 0 ? 'warn-t' : ''}">${fmt.inr(surplus)}</b>${surplus < 0 ? ' — a shortfall you would fund from savings or debt' : ''}.` : noProfile)}
        ${A('WHAT HAPPENS IF THE PRICE INCREASES?', `A ${fmt.pct(priceUp * 100, 0)} rise adds <b>${fmt.inr(amt * priceUp)}</b> to the price${finance ? ` and about ${fmt.inr(C.emi(amt * (1 + priceUp), rate, ten) - emi)} to the EMI` : ''}. Waiting has a cost too — compare it with the saving from delay.`)}
        ${A('WHAT HAPPENS IF YOU LOSE YOUR JOB?', m.income > 0 ? `After this ${fmt.inr(upfront + fee + tax)} outflow, liquid savings ${fmt.inr(afterSav)} cover about <b>${Number.isFinite(jobMonths) ? fmt.months(jobMonths) : '—'}</b> of essential expenses + debt + this new load.` : noProfile)}
        ${A('WHAT HAPPENS IF YOU NEED THE MONEY EARLY?', `${esc(d.exit)}<br>At an assumed exit cost of ${fmt.pct(ex * 100, 1)}, you would get back about <b>${fmt.inr(amt * (1 - ex))}</b> of ${fmt.inr(amt)}.`)}</div>
        <div class="card summary-card"><h3>DECISION SUMMARY</h3><div class="table-scroll"><table class="data"><tbody>
          <tr><th scope="row">Cost</th><td>${fmt.inr(total)} total over ${yrs} yrs (price ${fmt.inr(amt)})</td></tr>
          <tr><th scope="row">Recurring cost</th><td>${fmt.inr(rec + emi)}/month · ${fmt.inr((rec + emi) * 12)}/year</td></tr>
          <tr><th scope="row">Risk</th><td>${esc(riskLevel)}; ${esc(d.risks[0])}</td></tr>
          <tr><th scope="row">Liquidity</th><td>${esc(d.liq)}</td></tr>
          <tr><th scope="row">Fees</th><td>${fmt.inr(fee)} entered. ${esc(d.fee)}</td></tr>
          <tr><th scope="row">Taxes</th><td>${fmt.inr(tax)} entered. ${esc(d.tax)}</td></tr>
          <tr><th scope="row">Opportunity cost</th><td>${upfront > 0 || rec > 0 ? '≈ ' + fmt.inr(oppFV) + ' at a hypothetical ' + alt + '% (not guaranteed)' : '—'}</td></tr>
          <tr><th scope="row">Long-term impact</th><td>${m.income > 0 ? `Takes ${fmt.pct((rec + emi) / m.income * 100, 1)} of monthly income; one-time ${fmt.pct((upfront + fee + tax) / Math.max(1, m.liquid) * 100, 0)} of liquid savings.` : 'Add your income to see the share of income.'}</td></tr>
          <tr><th scope="row">Questions to verify</th><td><ul>${d.verify.map((q) => `<li>${esc(q)}</li>`).join('')}</ul></td></tr></tbody></table></div>
          </div>${adviser}
        <div class="card"><h3>THINGS PEOPLE FORGET</h3><div class="forget">${rows.map(([t, x]) => `<div class="forget-item"><h5>${esc(t)}</h5><p>${esc(x)}</p></div>`).join('')}</div></div>
        <div class="card"><h3>Checklist</h3><div id="d-chk"></div></div>`;
      const chk = { invest: 'invest', stock: 'stocks', mf: 'mf', gold: 'gold', crypto: 'crypto', vehicle: 'car', house: 'house', borrow: 'loan', eduloan: 'loan', card: 'card', insurance: 'insurance', business: 'business', spend: 'pay', subscribe: 'sign-subscription', travel: 'pay' }[cur];
      FOS.renderChecklist(out.querySelector('#d-chk'), chk);
    };
    root.querySelector('.chips').onclick = (e) => { const b = e.target.closest('[data-d]'); if (!b) return; cur = b.dataset.d; root.querySelectorAll('.chip').forEach((c) => { c.classList.toggle('on', c === b); c.setAttribute('aria-checked', c === b); }); buildForm(); };
    form.oninput = run; form.onchange = run; buildForm();
  };
})();
