/* ==========================================================================
   examples.js — one worked example at the bottom of every calculator.
   Each entry: [story, overrides, notes]
     story     a short real-life situation
     overrides values that must be fixed (fields whose default depends on YOUR data)
     notes     one plain sentence per field, in the same order as the calculator's fields
   The numbers in the result are computed live from the same formulas the calculator uses.
   ========================================================================== */
window.FOS = window.FOS || {};
(function () {
  'use strict';
  const E = {
    emi: ['Ravi takes a ₹10 lakh loan at 10% a year and will repay it over 5 years.', {}, ['The money the bank lends you (the principal).', 'The yearly interest rate written in the loan offer.', 'How many years you will take to repay. A longer time lowers the EMI but raises total interest.']],
    amortization: ['The same ₹10 lakh loan, but the bank raises the rate to 11.5% from month 13, and Ravi pays ₹5,000 extra every month plus a one-time ₹1 lakh in month 24.', { r2: 11.5, rm: 13, extra: 5000, lump: 100000, lm: 24 }, ['The original loan amount.', 'The rate you started with.', 'The original repayment period in years.', 'The new rate after the bank changes it. Leave equal to the old rate if nothing changes.', 'In which month the new rate starts. 0 means the rate never changes.', 'Extra rupees you add to every EMI to repay faster.', 'A single lump-sum prepayment, for example from a bonus.', 'The month in which that lump sum is paid.']],
    prepayment: ['Meera has a ₹50 lakh home loan at 8.75% for 20 years. She can add ₹5,000 every month and prepay ₹2 lakh in month 12.', {}, ['The home-loan amount.', 'The loan\'s yearly interest rate.', 'Original tenure in years.', 'The extra amount you will add to each EMI.', 'A one-time extra payment.', 'The month in which you make that one-time payment.', 'Some lenders charge a % on prepaid amounts; enter it, or 0 if there is none.']],
    loancost: ['A bank offers a ₹5 lakh personal loan at 12% for 3 years, with a 2% processing fee plus 18% GST on the fee and ₹1,000 of insurance.', { ins: 1000 }, ['The loan amount you apply for.', 'The interest rate printed in the offer.', 'The repayment period in years.', 'The processing fee as a % of the loan.', 'GST charged on that fee (18% is standard on fees).', 'Any insurance or documentation charges paid upfront.', 'The % charged if you close the loan early (used only for the foreclosure line).']],
    dti: ['Anita earns ₹80,000 a month, pays ₹20,000 in EMIs and ₹2,000 as card minimums.', {}, ['Your monthly income — use the same basis (gross or take-home) every time.', 'All loan EMIs you pay every month.', 'The minimum payments on your credit cards.', 'Any other debt payment, such as money repaid to a relative.']],
    utilization: ['Karan has credit cards with a combined limit of ₹3 lakh and currently owes ₹90,000.', {}, ['Add up the limits of all your cards.', 'The total you currently owe on them.']],
    cardpay: ['Sana owes ₹1 lakh on a card charging 42% a year. The minimum due is 5% of the balance (never below ₹200) and she can pay a fixed ₹10,000 a month.', { apr: 42 }, ['What you owe on the card now.', 'The yearly interest rate on the card statement (often 36–45%).', 'The minimum-due percentage shown on your statement.', 'The smallest minimum due the card ever asks for.', 'The fixed amount you plan to pay each month in the second scenario.', 'Any monthly fee or charge on the card.']],
    debtpayoff: ['Arun has a ₹50,000 card at 36%, a ₹2 lakh personal loan at 14% and a ₹5 lakh car loan at 9%, and can pay ₹30,000 a month in total.', {}, ['Balance of the first debt.', 'Interest rate of the first debt.', 'Balance of the second debt.', 'Interest rate of the second debt.', 'Balance of the third debt.', 'Interest rate of the third debt.', 'The total you can put towards all debts each month.']],
    'whatif-emi': ['Priya has ₹40 lakh left on a floating home loan at 8.5% with 15 years to go. The bank raises the rate to 10.5%.', {}, ['What you still owe today.', 'The rate you pay today.', 'The rate after the increase.', 'Months left on the loan today (15 years = 180).']],
    simple: ['₹1 lakh is lent at 7% simple interest for 5 years.', {}, ['The amount lent or invested.', 'The yearly interest rate.', 'How long, in years.']],
    compound: ['₹1 lakh is invested at 8% a year with interest added every quarter, for 10 years.', {}, ['The amount you invest.', 'The yearly rate.', 'How many years the money stays invested.', 'How often interest is added to the balance; more often means slightly more growth.']],
    inflation: ['A ₹1 lakh holiday costs ₹1 lakh today. What will the same holiday cost in 10 years at 6% inflation?', { i: 6 }, ['What the item or expense costs today.', 'How fast you expect prices to rise each year.', 'How many years ahead you are looking.']],
    fv: ['Neha has ₹1 lakh now, adds ₹5,000 every month, and assumes an 8% yearly return for 10 years.', {}, ['The money you already have.', 'The amount you add every month.', 'The yearly return you assume (an assumption, not a promise).', 'How many years you will do this.']],
    pv: ['Someone promises you ₹10 lakh in 10 years. At a 7% discount rate, what is that worth today?', {}, ['The amount you will receive in future.', 'The yearly rate used to bring future money back to today (inflation or expected return).', 'How many years until you receive it.']],
    cagr: ['An investment grew from ₹1 lakh to ₹2.5 lakh in 7 years. What steady yearly growth is that?', {}, ['What you invested at the start.', 'What it is worth now.', 'How many years passed.']],
    sip: ['Vikram invests ₹10,000 every month for 10 years and assumes 12% a year, with no yearly increase.', { inf: 6 }, ['The amount you invest every month.', 'How many years you keep investing.', 'The yearly return you assume. Real markets go up and down.', 'Increase your monthly amount by this % each year (0 = keep it fixed).', 'Used only to show the result in today\'s buying power.']],
    lumpsum: ['Rekha invests a ₹5 lakh bonus for 10 years. She tests a base return of 10% with 3 points either side.', {}, ['The one-time amount you invest.', 'How many years it stays invested.', 'The middle (base) return you assume.', 'How far the lower and higher scenarios are from the base, in percentage points.']],
    fd: ['Suresh puts ₹2 lakh in a 3-year FD at 6.5%, is in the 20% tax slab, and inflation is 6%.', { r: 6.5, inf: 6 }, ['The amount you deposit.', 'The FD\'s yearly rate.', 'The FD period in years.', 'How often the bank adds interest (quarterly is usual).', 'Your income-tax slab, to estimate tax on the interest.', 'Expected yearly inflation, to see if your buying power grew.']],
    rd: ['Latha saves ₹5,000 a month in a 5-year recurring deposit at 6.3%.', { r: 6.3 }, ['The amount you deposit every month.', 'The RD\'s yearly rate.', 'The number of months (5 years = 60).']],
    ppf: ['Mohan puts the full ₹1.5 lakh in PPF each year for 15 years at 7.1%.', { r: 7.1 }, ['The amount you deposit each year (the yearly limit applies).', 'The current PPF rate; it comes from Data & Sources.', 'How many years you keep depositing.']],
    nps: ['Divya, 30, puts ₹10,000 a month into NPS until 60 at an assumed 9%; 40% buys an annuity paying 6%.', { r: 9 }, ['Your monthly NPS contribution.', 'Your age today.', 'The age at which you retire.', 'The yearly return you assume on the NPS fund.', 'The share of the final corpus used to buy a pension (rules require a minimum share).', 'The yearly rate the annuity pays.']],
    fees: ['Imran invests ₹10,000 a month for 20 years at a 12% gross return. Fund A costs 0.3% a year; Fund B costs 1.8%.', {}, ['Your monthly investment.', 'Any lump sum you start with.', 'How many years you invest.', 'The return the funds earn before their fees.', 'Yearly fee of the cheaper fund.', 'Yearly fee of the costlier fund.']],
    absreturn: ['Bought shares for ₹1 lakh, now worth ₹1.2 lakh, after paying ₹500 in charges.', {}, ['What you paid.', 'What it is worth, or what you sold it for.', 'Brokerage, taxes and other costs you paid.']],
    dividend: ['A company pays ₹10 a year per share; the share costs ₹400 and you own 100 shares.', {}, ['The dividend the company pays per share each year.', 'The current price of one share.', 'How many shares you own.']],
    pe: ['A company earns ₹100 crore profit, has 10 crore shares (price ₹500) and ₹800 crore shareholders\' equity.', {}, ['The current price of one share.', 'The company\'s yearly net profit in crore rupees.', 'Number of shares in crore.', 'Shareholders\' equity (book value) in crore rupees.']],
    allocation: ['Pooja holds ₹5 lakh in equity, ₹3 lakh in debt, ₹1 lakh in gold and ₹1 lakh in cash.', {}, ['Value of shares and equity funds.', 'Value of FDs, bonds and debt funds.', 'Value of gold held as an investment.', 'Investment property (not the home you live in).', 'Cash and savings-account balance.', 'Anything else, including crypto.']],
    bond: ['A ₹1,000 bond pays 8% a year for 5 years. The market now demands an 8% yield, and you ask what happens if yields move.', {}, ['The amount repaid at maturity.', 'The yearly interest the bond pays, as a % of face value.', 'The return investors currently require.', 'Years until the bond matures.', 'How many times a year the coupon is paid.']],
    goldcalc: ['Tara has ₹5 lakh and compares jewellery, a coin and a gold ETF over 10 years, assuming gold rises 7% a year.', {}, ['The money you will spend on gold.', 'How long you will hold it.', 'The yearly gold price rise you assume.', 'Making charge plus wastage on jewellery.', 'GST on gold.', 'What the jeweller deducts if you sell the jewellery back.', 'Yearly cost of a locker, as a % of the value.', 'Yearly fee of the gold ETF or fund.']],
    cryptoscen: ['Dev considers putting ₹1 lakh into crypto. His total net worth is ₹10 lakh. See the outcomes from +100% to −100%.', { tax: 30, tds: 1 }, ['The amount you would invest.', 'Trading fee plus spread each time you buy or sell.', 'Tax on gains (from the tax data).', 'TDS deducted on selling (from the tax data).', 'Everything you own minus everything you owe, to show how big the risk is.']],
    oppcost: ['Kavita spends ₹50,000 on a gadget. What might that money have become if saved or invested?', {}, ['The one-time amount you are about to spend.', 'A regular monthly amount, if the spending repeats (0 if it is one-time).']],
    edu: ['A degree costs ₹20 lakh today and will start in 8 years; fees rise 8% a year; you can save ₹10,000 a month at an assumed 9%.', {}, ['The course cost today.', 'How fast you expect fees to rise each year.', 'Years before you need the money.', 'Money already set aside for this.', 'The yearly return you assume on these savings.', 'What you can save every month.']],
    marriage: ['A family event costing ₹15 lakh today is planned in 4 years; costs rise 8%; you can save ₹15,000 a month.', {}, ['Today\'s estimate of the cost.', 'Expected yearly rise in that cost.', 'Years until the event.', 'What you have already saved for it.', 'The yearly return you assume.', 'What you can save every month.']],
    child: ['Their child is 2 years old and needs ₹25 lakh (today\'s cost) at age 18. Costs rise 8%; the family saves ₹8,000 a month.', {}, ['The child\'s age today.', 'The age at which the money is needed.', 'The cost today.', 'Expected yearly cost increase.', 'What is already saved for this goal.', 'The yearly return you assume.', 'What you save every month.']],
    goal: ['Ishaan wants a ₹1 lakh laptop in 2 years. Prices rise 5% a year; he has ₹10,000 saved and assumes a safe 6% return.', {}, ['The price today.', 'What you have already saved.', 'When you need it, in years.', 'How much the price might rise each year.', 'The return you assume; use a low number for short goals.']],
    retirement: ['Anil, 30, spends ₹50,000 a month, has ₹5 lakh invested, adds ₹20,000 a month, and plans to retire at 60 and live to 85.', { ret: 60, inf: 6, pr: 7, life: 85 }, ['Your age today.', 'The age you want to stop working.', 'What you spend each month today.', 'Yearly inflation you assume.', 'What you have invested today.', 'What you invest every month.', 'The yearly return you assume until retirement.', 'The yearly return you assume after retirement (usually lower).', 'How long you plan for, as an age.']],
    fi: ['Rohit spends ₹50,000 a month, has ₹5 lakh invested, adds ₹30,000 a month, and uses a 3.5% withdrawal rate.', { inf: 6 }, ['Your monthly spending.', 'What you have invested today.', 'What you invest every month.', 'The yearly return you assume.', 'Yearly inflation you assume.', 'The share of your corpus you plan to withdraw each year once independent.']],
    emergency: ['Nisha spends ₹30,000 on essentials and ₹10,000 on EMIs each month, has one dependant, no job stability worries, health insurance, ₹50,000 saved and can add ₹5,000 a month.', {}, ['Rent, food, bills — things you must pay.', 'EMIs and minimum card payments.', 'How steady your income is.', 'Number of people who depend on your income.', 'Whether you have adequate health insurance.', 'Emergency savings you already hold.', 'What you can add each month.']],
    'whatif-job': ['Ajay has ₹2 lakh in savings, spends ₹30,000 on essentials and pays ₹10,000 in EMIs. How long could he last without a salary?', { sav: 200000, ess: 30000, debt: 10000 }, ['Cash you could use quickly.', 'Essential monthly spending.', 'EMIs you must keep paying.', 'Any other income during the gap, such as a spouse\'s salary.', 'Any monthly benefit you would receive.']],
    networthcalc: ['Leela has ₹1 lakh in bank, ₹1 lakh in FDs and ₹1 lakh in investments, and owes nothing.', {}, ['Savings and current account balances plus cash.', 'Fixed and recurring deposits.', 'Shares, mutual funds, EPF, PPF.', 'Gold you own.', 'Market value of property.', 'What you could sell your vehicle for.', 'Any other asset.', 'Unpaid credit-card bills.', 'Personal loans.', 'Vehicle loan balance.', 'Home-loan balance.', 'Education-loan balance.', 'Any other debt.']],
    lifesim: ['Sameer, 25, earns ₹50,000 a month (rising 7% a year), spends ₹30,000, has ₹1 lakh saved, no debt, retires at 60 and is modelled to 85.', { inf: 6, pr: 7, ret: 60, life: 85 }, ['Your age today.', 'Your monthly take-home pay.', 'How much your pay rises each year.', 'Your monthly spending.', 'Yearly inflation you assume.', 'Savings and investments you have now.', 'Debt you have now.', 'Interest rate on that debt.', 'Years you will take to repay it.', 'Yearly return before retirement.', 'Yearly return after retirement.', 'Age at which pay stops.', 'The last age to simulate.']],
    savingsrate: ['Riya earns ₹60,000 and spends ₹40,000 each month.', { inc: 60000, exp: 40000 }, ['Your monthly take-home income.', 'What you spend each month, not counting money you invest.']],
    salary: ['Nikhil\'s offer says ₹12 lakh CTC, with 40% basic, ₹1 lakh variable, under the new tax regime.', { epf: 12, eepf: 12, grat: 4.81, pt: 200 }, ['The yearly cost-to-company in your offer.', 'Basic pay as a share of CTC.', 'The company\'s PF contribution as a % of basic.', 'Your own PF contribution as a % of basic.', 'Gratuity accrual as a % of basic.', 'The part of CTC that depends on performance.', 'Insurance and similar benefits counted in CTC.', 'State professional tax per month.', 'Any other monthly deduction.', 'The tax regime you will choose.', 'Deductions you will claim if you choose the old regime.']],
    subscription: ['A family pays ₹499 a month for each of 5 streaming and app subscriptions, and prices rise 8% a year.', {}, ['The price of one billing.', 'How often it is billed.', 'How many such subscriptions you have.', 'How much the price rises each year.']],
    incometax: ['A salaried person earns ₹15 lakh, has ₹50,000 of interest income and could claim ₹2 lakh of old-regime deductions.', { yr: 'FY2025-26' }, ['The tax year whose rules to use.', 'Your yearly salary or business income.', 'Interest, rent and other income.', 'Total deductions you would claim under the old regime.']],
    capgains: ['Hema bought shares for ₹5 lakh and sold them for ₹8 lakh after two years.', { yr: 'FY2025-26' }, ['The tax year whose rules to use.', 'What you sold.', 'What you paid.', 'What you sold it for.', 'Your income-tax slab, used for items taxed at slab rate.']],
    cover: ['Gopal earns ₹12 lakh a year, has a ₹20 lakh home loan, wants ₹10 lakh for his child\'s education, and has ₹5 lakh of savings.', { inc: 1200000, inf: 6, debt: 2000000, goals: 1000000, assets: 500000 }, ['The income your family relies on.', 'For how many years they would need support.', 'The safe return your family could earn on the payout.', 'Yearly inflation.', 'Loans that would need to be cleared.', 'Future big goals to be funded.', 'Savings and investments you already have.', 'Life cover you already hold.', 'Your health cover, for reference only.']],
    rentbuy: ['A ₹60 lakh flat (₹12 lakh down, 8.75% for 20 years) versus renting a similar home at ₹20,000 a month, compared after 15 years.', { lr: 8.75 }, ['The price of the home.', 'Money you pay upfront.', 'The home-loan rate.', 'Loan length in years.', 'Rent you would pay for a similar home.', 'How much rent rises each year.', 'How much the property value rises each year.', 'Monthly maintenance and society charges.', 'Yearly property tax as a % of price.', 'Stamp duty, registration and brokerage as a % of price.', 'The % cost when you eventually sell.', 'What you could earn investing the money instead of buying.', 'The number of years to compare.']],
    car: ['A ₹9 lakh car with ₹1.8 lakh down, a 5-year loan at 9.5%, driven 800 km a month.', { r: 9.5 }, ['The on-road price.', 'What you pay upfront.', 'The loan rate.', 'The loan length.', 'Yearly insurance premium.', 'How far you drive each month.', 'Kilometres the car runs per litre.', 'Price of a litre of fuel.', 'Yearly servicing and repairs.', 'Monthly parking and tolls.', 'One-time road tax or registration if not in the price.', 'How much value the car loses each year.']],
    breakeven: ['A tiffin business has ₹1 lakh of monthly fixed costs; each meal costs ₹60 to make and sells for ₹100.', {}, ['Costs you pay every month regardless of sales (rent, salaries, EMI).', 'The cost of making or delivering one unit.', 'The price you charge for one unit.']],
    roi: ['A shop earns ₹50 lakh revenue, with ₹30 lakh direct costs, ₹10 lakh operating costs, ₹2 lakh interest and tax, on ₹20 lakh invested.', {}, ['Total sales for the year.', 'Costs directly tied to making the sales.', 'Rent, salaries and other running costs.', 'Interest, tax and other charges.', 'Money invested in the business.']],
    runway: ['A startup has ₹12 lakh in the bank, spends ₹3 lakh a month and earns ₹1 lakh a month.', {}, ['Cash available now.', 'Monthly spending.', 'Monthly money received from customers.', 'How fast you expect monthly revenue to grow.']],
    'whatif-salary': ['Jay takes home ₹60,000, spends ₹40,000 and gets a 10% raise; he decides to save half of it.', { inc: 60000, exp: 40000 }, ['Your monthly take-home pay now.', 'Your monthly spending now.', 'The raise you receive.', 'The share of the raise you will save instead of spend.', 'The yearly return you assume on it.', 'How many years to look ahead.']],
    'whatif-inflation': ['Lata has ₹10 lakh and monthly expenses of ₹50,000; what happens over 15 years at inflation of 3% to 10%?', {}, ['A sum of money you hold today.', 'What you spend each month today.', 'How many years ahead.']],
    'whatif-fall': ['Ben has a ₹10 lakh portfolio. If it falls 50%, how much growth is needed to recover and can he still fund ₹2 lakh needed next year?', { val: 1000000 }, ['The current value of your investments.', 'How far they fall, in %.', 'The yearly growth you assume while recovering.', 'Money you must spend within a year.']],
    'whatif-rent': ['Rent is ₹20,000 a month, rises 8% a year, for 10 years, against an income of ₹80,000.', { inc: 80000 }, ['What you pay now.', 'The yearly rise in rent.', 'How many years to look ahead.', 'Your monthly income today.']],
    'whatif-invest': ['Compare investing ₹5,000, ₹10,000, ₹15,000 and ₹20,000 a month for 15 years at an assumed 12%.', { inf: 6 }, ['How long you will invest.', 'The yearly return you assume.', 'Inflation, to show today\'s buying power.']],
    'whatif-retire': ['Sonia, 30, spends ₹50,000 a month, has ₹5 lakh invested, adds ₹25,000 a month; she compares retiring at different ages.', { inf: 6, pr: 7, life: 85 }, ['Your age today.', 'What you spend each month now.', 'Yearly inflation.', 'What you have invested.', 'What you invest each month.', 'Yearly return before retiring.', 'Yearly return after retiring.', 'Age you plan for.']],
    afford: ['Raj earns ₹1 lakh gross (₹85,000 take-home) and wants a ₹9 lakh car with 20% down over 4 years at 9.5%, with ₹6,000 running costs.', { rate: 9.5, gross: 100000, net: 85000, emis: 0, liquid: 500000, ess: 35000 }, ['What you are buying; it changes the guideline used.', 'The full price you will pay.', 'The share paid upfront.', 'Loan period in years.', 'The loan\'s yearly rate.', 'Your monthly income before tax and deductions.', 'The amount that reaches your account each month.', 'Fuel, insurance and maintenance for a vehicle; maintenance for a home.', 'EMIs you already pay.', 'Cash you can get at quickly today.', 'Your monthly essential expenses.']],
    taxopt: ['Shalini earns ₹15 lakh, pays ₹20,000 rent in a metro, has ₹2.4 lakh HRA, ₹1.5 lakh of 80C and ₹30,000 other income.', { salary: 1500000 }, ['Your yearly gross salary.', 'Interest or other income.', 'Your yearly basic pay (on the salary slip).', 'The HRA you receive each year.', 'Rent you pay every month.', 'Metro cities get a higher HRA limit.', '80C investments already made.', 'Extra NPS contribution by you.', 'NPS contribution by your employer.', 'Health-insurance premium for you and family.', 'Health-insurance premium for parents.', 'Whether your parents are 60 or older.', 'Interest on a home loan for the home you live in.', 'Interest paid on an education loan.']],
    hra: ['Shalini has ₹6 lakh basic, receives ₹2.4 lakh HRA and pays ₹20,000 rent in a metro.', {}, ['Yearly basic pay.', 'Yearly HRA received.', 'Monthly rent.', 'Metro or non-metro, which changes the limit.']]
  };

  function fieldValue(f, ov) {
    if (f.id in ov) return ov[f.id];
    return typeof f.def === 'function' ? f.def() : f.def;
  }
  FOS.exampleValues = function (id) { const c = FOS.calcs[id], ex = E[id]; if (!c || !ex) return {}; const v = {}; c.fields.forEach((f) => { v[f.id] = fieldValue(f, ex[1]); }); return v; };
  FOS.EXAMPLES = E;

  FOS.exampleHTML = function (id) {
    const c = FOS.calcs[id], ex = E[id]; if (!c || !ex) return '';
    const esc = FOS.ui.esc, fmt = FOS.fmt, vals = FOS.exampleValues(id);
    let res; try { res = c.compute(Object.assign({}, vals, Object.fromEntries(c.fields.filter((f) => f.type === 'sel').map((f) => [f.id, isNaN(+vals[f.id]) ? vals[f.id] : +vals[f.id]])))); } catch (e) { res = { summary: [] }; }
    const show = (f, v) => { if (f.type === 'sel') { const o = f.options.find((x) => String(Array.isArray(x) ? x[0] : x) === String(v)); return Array.isArray(o) ? o[1] : String(v); } if (f.type === 'money') return fmt.inr(+v); if (f.type === 'pct') return v + '%'; if (f.type === 'yrs') return v + (+v === 1 ? ' year' : ' years'); if (f.type === 'mon') return v + ' months'; return String(v); };
    const rows = c.fields.map((f, i) => `<li><div class="ex-h"><b>${esc(f.label)}</b><span class="ex-v">${esc(show(f, vals[f.id]))}</span></div><p>${esc(ex[2][i] || '')}</p></li>`).join('');
    const out = (res.summary || []).slice(0, 6).map((s) => `<li>${esc(s.l)}: <b>${esc(FOS.showVal ? FOS.showVal(s.f, s.v) : String(s.v))}</b></li>`).join('');
    return `<section class="card example" aria-label="Worked example"><h3>Worked example</h3><p class="story">${esc(ex[0])}</p>
      <ul class="ex-fields">${rows}</ul>
      ${out ? `<h4>What this example gives</h4><ul>${out}</ul>` : ''}<div class="row-actions"><button class="btn primary" data-a="example">Try this example in the calculator</button></div></section>`;
  };
})();
