/* ==========================================================================
   jargon.js — "Money Words A–Z": every short form and unfamiliar word you meet in
   banks, cards, loans, investing, insurance, income tax, salary, property, vehicles, GST
   and government schemes. Plain meaning first. Rates/limits are NOT stored here
   (they change) — this file only explains words.
   Entry: [term, full form (or ''), meaning in plain words]
   ========================================================================== */
window.FOS = window.FOS || {};
(function () {
  'use strict';
  const J = (FOS.JARGON = []);
  const add = (cat, rows) => rows.forEach((r) => J.push({ t: r[0], full: r[1] || '', m: r[2], cat }));
  FOS.JARGON_CATS = ['Banking', 'Payments', 'Cards & credit', 'Loans', 'Investing', 'Mutual funds', 'Stocks & markets', 'Insurance', 'Income tax', 'Salary & PF', 'Property', 'Vehicle', 'GST & business', 'Government & regulators', 'Everyday money words'];

  add('Banking', [
    ['KYC', 'Know Your Customer', 'Identity and address verification every bank, broker and fund house must do before you can open an account or invest. Done once per institution (or once for all mutual funds via a KRA).'],
    ['CKYC', 'Central KYC Registry', 'A government database of your verified KYC, so a new bank or insurer can reuse it. You get a 14-digit CKYC number.'],
    ['KRA', 'KYC Registration Agency', 'Agency that stores your KYC for mutual funds and brokers so you complete it only once (CAMS, CVL, NDML and others).'],
    ['IFSC', 'Indian Financial System Code', '11-character code of a bank branch (4 letters for the bank, a 0, then 6 characters for the branch). Needed for NEFT, RTGS and IMPS transfers.'],
    ['MICR', 'Magnetic Ink Character Recognition', '9-digit code printed at the bottom of a cheque identifying city, bank and branch so machines can read it.'],
    ['CIF', 'Customer Information File', 'Your customer ID inside a bank. All your accounts at that bank link to it.'],
    ['A/c', 'Account', 'Short for account.'],
    ['SB', 'Savings Bank account', 'Ordinary savings account. Interest is paid on the daily balance.'],
    ['CA', 'Current Account', 'Business account with no interest, higher charges and overdraft facility.'],
    ['BSBDA', 'Basic Savings Bank Deposit Account', 'Zero-balance basic account with limited free services, meant for first-time account holders.'],
    ['PMJDY', 'Pradhan Mantri Jan Dhan Yojana', 'Government scheme for zero-balance accounts with RuPay debit card and small accident cover.'],
    ['NRE', 'Non-Resident External account', 'Rupee account for NRIs holding foreign earnings. Interest is tax-free in India and the money can go back abroad.'],
    ['NRO', 'Non-Resident Ordinary account', 'Rupee account for NRIs to hold India-sourced income such as rent. Interest is taxable.'],
    ['FCNR', 'Foreign Currency Non-Resident account', 'NRI fixed deposit held in a foreign currency, so there is no exchange-rate risk.'],
    ['NRI', 'Non-Resident Indian', 'An Indian citizen who lives abroad for work or business (tax status depends on days spent in India).'],
    ['FD', 'Fixed Deposit', 'You lock money with a bank for a set period at a fixed rate. Breaking it early usually costs 0.5–1% of the rate.'],
    ['RD', 'Recurring Deposit', 'You deposit a fixed amount every month for a fixed period and get a fixed rate, like a savings habit with a guarantee.'],
    ['TD', 'Term Deposit', 'Another name for a fixed deposit; post offices use “TD”.'],
    ['Sweep-in FD', '', 'An FD linked to your savings account: balance above a set limit moves into an FD automatically and comes back when you need it.'],
    ['Cumulative FD', '', 'Interest is added back and paid at maturity together with the principal.'],
    ['Non-cumulative FD', '', 'Interest is paid out monthly, quarterly or yearly while the principal stays locked.'],
    ['Maturity', '', 'The date on which a deposit, bond or policy ends and the money is paid back.'],
    ['Premature withdrawal', '', 'Taking money out of an FD before maturity. The bank cuts the interest rate and may charge a penalty.'],
    ['Lien', '', 'A bank’s legal hold on your deposit or asset because it has lent against it. You cannot withdraw until the loan is cleared.'],
    ['Overdraft', 'OD', 'Spending more than your balance up to an agreed limit; interest is charged only on the amount used and for the days used.'],
    ['Minimum balance (AMB / MAB)', 'Average / Monthly Average Balance', 'The balance your account must maintain; if you fall short the bank charges a penalty.'],
    ['Nominee', '', 'The person who receives your account, FD, policy or fund if you die. A nominee is a trustee for the legal heirs; also keep a will.'],
    ['Joint account — Either or Survivor', '', 'Any holder can operate it alone; if one dies, the survivor receives the money.'],
    ['Dormant / inoperative account', '', 'An account with no customer-initiated transaction for about 2 years. It is frozen until you complete KYC again.'],
    ['Passbook', '', 'Booklet in which the bank prints your transactions. Mini-statements and apps have mostly replaced it.'],
    ['Cheque', '', 'A written order to your bank to pay a person a stated amount from your account.'],
    ['Cheque bounce / dishonour', '', 'A cheque returned unpaid, usually for insufficient funds. It attracts bank charges and can lead to a case under Section 138 of the Negotiable Instruments Act.'],
    ['Crossed cheque / A/c payee', '', 'Two parallel lines on a cheque mean the money can be credited only to a bank account, not paid in cash.'],
    ['PDC', 'Post-Dated Cheque', 'A cheque dated in the future, often given for EMIs or rent.'],
    ['DD', 'Demand Draft', 'A prepaid bank instrument that guarantees payment to the named person; the bank has already taken the money from you.'],
    ['Banker’s cheque / Pay order', '', 'A cheque issued by the bank itself against your money; safer to accept than a personal cheque.'],
    ['Locker', 'Safe deposit locker', 'A rented box in the bank’s vault. Banks are not automatically liable for contents; insure valuables yourself.'],
    ['DICGC', 'Deposit Insurance and Credit Guarantee Corporation', 'RBI subsidiary that insures bank deposits up to ₹5 lakh per depositor per bank (principal and interest together).'],
    ['RBI', 'Reserve Bank of India', 'India’s central bank. Regulates banks and NBFCs, controls interest policy and issues currency.'],
    ['SFB', 'Small Finance Bank', 'A bank for small borrowers and savers (AU, Equitas, Ujjivan, etc.), usually with higher deposit rates; deposits are still DICGC-insured.'],
    ['PSU bank', 'Public Sector Undertaking bank', 'A bank majority-owned by the government, such as SBI, PNB or Bank of Baroda.'],
    ['Co-operative bank', '', 'A bank owned by its members and regulated by RBI and state registrars. Check that it is DICGC-insured and RBI-licensed.'],
    ['NBFC', 'Non-Banking Financial Company', 'A lender that is not a bank. It gives loans but cannot hold savings accounts or cheque facilities.'],
    ['HFC', 'Housing Finance Company', 'An NBFC that gives home loans (for example LIC Housing Finance).'],
    ['Basis point (bps)', '', 'One hundredth of a percent. 25 bps = 0.25%. 100 bps = 1%.'],
    ['Repo rate', '', 'The rate at which RBI lends to banks. When it falls, loans linked to it become cheaper.'],
    ['Reverse repo / SDF', 'Standing Deposit Facility', 'The rate at which banks park spare money with RBI.'],
    ['MCLR', 'Marginal Cost of Funds based Lending Rate', 'An internal benchmark banks use to price older floating loans. Newer loans use the external benchmark (repo-linked).'],
    ['EBLR / RLLR', 'External Benchmark Lending Rate / Repo-Linked Lending Rate', 'A loan rate that moves directly with the RBI repo rate plus a spread the bank fixes.'],
    ['Spread', '', 'The bank’s margin added over the benchmark. A loan at repo + 2.5% has a spread of 2.5%.'],
    ['CRR', 'Cash Reserve Ratio', 'Share of deposits banks must keep with RBI in cash.'],
    ['SLR', 'Statutory Liquidity Ratio', 'Share of deposits banks must hold in government securities, gold or cash.'],
    ['NPA', 'Non-Performing Asset', 'A loan on which the borrower has not paid for 90 days or more.'],
    ['Settlement (loan)', '', 'You pay less than owed and the lender closes the account as “settled”. It damages your credit report badly.'],
    ['Write-off', '', 'A lender removes a loan from its books as unrecoverable. You still owe the money and it hurts your credit report.'],
    ['Bank holiday / cut-off time', '', 'The time after which a transaction is processed on the next working day.']
  ]);

  add('Payments', [
    ['UPI', 'Unified Payments Interface', 'Instant bank-to-bank payment system using a mobile app and a PIN. Free for most users.'],
    ['VPA / UPI ID', 'Virtual Payment Address', 'Your payment address like name@bank, so you don’t have to share your account number.'],
    ['NPCI', 'National Payments Corporation of India', 'The organisation that runs UPI, RuPay, IMPS, FASTag and Aadhaar-based payments.'],
    ['NEFT', 'National Electronic Funds Transfer', 'Bank transfer processed in batches throughout the day; no minimum amount.'],
    ['RTGS', 'Real Time Gross Settlement', 'Instant bank transfer for large amounts (minimum ₹2 lakh).'],
    ['IMPS', 'Immediate Payment Service', 'Instant 24×7 bank transfer using mobile number, account number or MMID.'],
    ['MMID', 'Mobile Money Identifier', '7-digit code linked to your mobile number for IMPS transfers.'],
    ['NACH', 'National Automated Clearing House', 'The system that collects your EMIs, SIPs and insurance premiums automatically from your bank account.'],
    ['ECS', 'Electronic Clearing Service', 'Older name for automatic debit; NACH has replaced it.'],
    ['e-Mandate / AutoPay', '', 'A standing instruction you approve once so a merchant or lender can debit a set amount on due dates.'],
    ['BBPS', 'Bharat Bill Payment System', 'One platform to pay electricity, gas, water, mobile and credit card bills (shown as “Bharat Connect”).'],
    ['FASTag', '', 'A prepaid sticker on the windshield that pays highway tolls automatically. It must be linked to the vehicle and KYC’d.'],
    ['QR code', 'Quick Response code', 'A square code. Scanning it to pay sends money out; you never need to scan or enter a PIN to receive money.'],
    ['OTP', 'One-Time Password', 'A single-use code sent to your phone. Never share it with anyone, including bank staff.'],
    ['PIN', 'Personal Identification Number', 'Secret number for your card or UPI. Entering it moves money out of your account.'],
    ['CVV', 'Card Verification Value', 'The 3-digit code on the back of your card. Never share it.'],
    ['3D Secure', '', 'The extra OTP step when paying online with a card.'],
    ['Tokenisation', '', 'Your card number is replaced by a secure token for saved cards, so merchants don’t store the real number.'],
    ['Chargeback', '', 'A dispute process in which the card network forces a refund when a purchase was fraudulent or not delivered.'],
    ['MDR', 'Merchant Discount Rate', 'The fee a shop pays the bank for accepting card payments.'],
    ['Wallet / PPI', 'Prepaid Payment Instrument', 'Money loaded into an app (Paytm, PhonePe wallet, etc.). Check KYC limits.'],
    ['COD', 'Cash on Delivery', 'Paying when the item arrives.'],
    ['Escrow', '', 'A neutral account that holds payment until both sides meet their conditions, used in property and online marketplaces.'],
    ['SWIFT', 'Society for Worldwide Interbank Financial Telecommunication', 'Network and bank code (BIC) used for international transfers.'],
    ['LRS', 'Liberalised Remittance Scheme', 'RBI scheme allowing an individual to send up to US$250,000 abroad per financial year for permitted purposes.'],
    ['TCS', 'Tax Collected at Source', 'Tax a seller collects from you at the time of certain payments (foreign remittance, overseas tour packages). You can claim it as credit in your return.']
  ]);

  add('Cards & credit', [
    ['Credit limit', '', 'The maximum you can owe on a card at any time.'],
    ['Billing cycle', '', 'The roughly 30-day period whose purchases are added to one statement.'],
    ['Statement date', '', 'The day the bill for the cycle is generated.'],
    ['Due date', '', 'The last day to pay without a late fee.'],
    ['Total amount due', 'TAD', 'Everything you owe. Pay this by the due date to pay zero interest.'],
    ['Minimum amount due', 'MAD', 'The smallest payment that avoids a late fee; interest still builds on the rest.'],
    ['Grace period / interest-free period', '', 'The 20–50 days between a purchase and the due date during which no interest is charged, if you paid the previous bill in full.'],
    ['Revolving credit', '', 'Carrying a card balance from month to month and paying interest.'],
    ['Cash advance', '', 'Withdrawing cash on a credit card. Costs a fee plus interest from day one.'],
    ['EMI conversion', '', 'Turning a card purchase into instalments. It is a loan with its own fee and interest.'],
    ['No-cost EMI', '', 'An instalment offer where the interest is hidden as a lost discount or added to the price.'],
    ['BNPL', 'Buy Now Pay Later', 'Short-term credit at checkout. Late fees and credit-report effects apply.'],
    ['Utilisation', 'Credit utilisation ratio', 'Share of your total limit you are using. Under 30% looks healthy to lenders.'],
    ['Reward points / Cashback', '', 'Rewards a card gives on spending. Real value is usually 0.5–2% and often capped.'],
    ['Annual fee / Joining fee', '', 'Yearly or one-time charge on a card; often waived if you spend a set amount.'],
    ['Forex mark-up', '', 'The extra % (usually about 3.5%) a card charges on foreign-currency spending.'],
    ['MITC', 'Most Important Terms and Conditions', 'A short summary of a card’s key fees and rules that the bank must give you.'],
    ['Credit score', '', 'A 3-digit number (300–900) summarising your repayment record, used by lenders to decide on loans and rates.'],
    ['CIBIL', 'Credit Information Bureau (India) Limited', 'The best-known credit bureau, now TransUnion CIBIL. Others are Experian, Equifax and CRIF High Mark.'],
    ['Credit report', '', 'The full history of your loans and cards held by a bureau. One free copy per bureau per year.'],
    ['DPD', 'Days Past Due', 'How many days a payment is late. It is recorded month by month on your report.'],
    ['Hard enquiry', '', 'A lender checking your report because you applied for credit. Many in a short time can lower your score.'],
    ['Soft enquiry', '', 'A check that doesn’t affect your score, such as looking at your own report.'],
    ['Secured card', '', 'A card issued against a fixed deposit, used to build credit history.'],
    ['Add-on card', '', 'An extra card for a family member, billed to the same account.'],
    ['Co-branded card', '', 'A card issued by a bank jointly with a brand (airline, e-commerce) giving special rewards.'],
    ['Pre-approved offer', '', 'A bank’s invitation to take a loan or card it has pre-checked. It isn’t free money; fees and rates still apply.']
  ]);

  add('Loans', [
    ['EMI', 'Equated Monthly Instalment', 'The fixed amount you pay every month to repay a loan with interest.'],
    ['Principal', '', 'The amount you borrowed, not including interest.'],
    ['Tenure', '', 'How long you have to repay the loan.'],
    ['Interest rate — Fixed', '', 'Does not change during the fixed period.'],
    ['Interest rate — Floating', '', 'Changes when the benchmark (repo) changes.'],
    ['Reducing balance', '', 'Interest is charged on what you still owe, so interest falls as you repay.'],
    ['Flat rate', '', 'Interest is charged on the original amount for the whole term; it looks cheap but is effectively much higher.'],
    ['APR / IRR', 'Annual Percentage Rate / Internal Rate of Return', 'The true yearly cost of a loan, including fees. Compare lenders on this number.'],
    ['Amortisation', '', 'The schedule that shows how each EMI splits into interest and principal.'],
    ['Processing fee', '', 'One-time fee for handling the loan (0.25–2% plus GST).'],
    ['Foreclosure', '', 'Paying off the entire loan before the end. Floating-rate loans for individuals have no penalty.'],
    ['Part-prepayment', '', 'Paying a lump sum towards principal to cut interest or tenure.'],
    ['Moratorium', '', 'A period during which you don’t pay EMIs (for example during study). Interest usually keeps building.'],
    ['Pre-EMI', '', 'Paying only interest on the part of a home loan disbursed so far, while the building is under construction.'],
    ['Disbursement', '', 'The bank paying out the loan to you or the seller.'],
    ['Sanction letter', '', 'The bank’s written approval stating amount, rate, tenure, fees and conditions.'],
    ['LTV', 'Loan-to-Value ratio', 'The share of the asset’s value the bank lends. A 75% LTV means you pay 25% as down payment.'],
    ['Down payment / Margin money', '', 'The part of the price you pay from your own pocket.'],
    ['FOIR', 'Fixed Obligation to Income Ratio', 'Share of your income that goes to fixed debt payments. Banks like it under 40–50%.'],
    ['DTI', 'Debt-to-Income ratio', 'Your monthly EMIs divided by monthly income. Keep it below 35–40%.'],
    ['Collateral / Security', '', 'An asset (house, gold, FD) the lender can sell if you don’t repay.'],
    ['Secured vs unsecured loan', '', 'Secured has collateral and a lower rate; unsecured (personal loan, card) has none and costs more.'],
    ['Guarantor / Co-borrower', '', 'A person who shares the responsibility for repaying. A guarantor’s credit report is affected too.'],
    ['Hypothecation', '', 'The lender’s claim on a vehicle or equipment you bought with the loan. It is noted on the RC until the loan is closed.'],
    ['Mortgage', '', 'A loan secured by a property; the lender holds the title documents until closing.'],
    ['Equitable mortgage', '', 'A mortgage created by depositing the original title deeds with the lender.'],
    ['LAP', 'Loan Against Property', 'A loan taken by mortgaging a property you own, at a rate lower than personal loans.'],
    ['Balance transfer', '', 'Moving your loan or card balance to another lender at a lower rate (watch the new fees).'],
    ['Top-up loan', '', 'An extra loan from the same lender on top of an existing home loan.'],
    ['NOC', 'No Objection Certificate', 'A letter from a lender, society or authority stating it has no claim or objection. After repaying a loan you get a NOC and no-dues certificate.'],
    ['Pre-approved loan', '', 'An offer of a loan based on your profile; the final approval needs documents.'],
    ['Mudra loan', 'MUDRA (Micro Units Development & Refinance Agency)', 'Collateral-free small business loans: Shishu (up to ₹50,000), Kishore (up to ₹5 lakh) and Tarun (up to ₹10 lakh).'],
    ['CGTMSE', 'Credit Guarantee Fund Trust for Micro and Small Enterprises', 'A government guarantee that lets small businesses get loans without collateral.'],
    ['MSME', 'Micro, Small and Medium Enterprises', 'Business size classes by investment and turnover; they get cheaper loans and benefits.'],
    ['Udyam', '', 'The free online registration that makes your business an officially recognised MSME.'],
    ['CSIS', 'Central Sector Interest Subsidy', 'A scheme that pays the interest on an education loan during the study period for eligible low-income students.'],
    ['SARFAESI', 'Securitisation and Reconstruction of Financial Assets and Enforcement of Security Interest Act', 'Law allowing banks to take over and sell the secured asset of a defaulting borrower without going to court first.']
  ]);

  add('Investing', [
    ['SIP', 'Systematic Investment Plan', 'You invest a fixed amount at fixed intervals (usually monthly) into a mutual fund.'],
    ['STP', 'Systematic Transfer Plan', 'Moving money from one fund (usually debt) into another (usually equity) in instalments.'],
    ['SWP', 'Systematic Withdrawal Plan', 'Taking a fixed amount out of a fund regularly, like a pension.'],
    ['Lumpsum', '', 'Investing a large amount in one go.'],
    ['Step-up SIP', '', 'A SIP whose amount you increase by a set % every year.'],
    ['Rupee-cost averaging', '', 'Buying more units when prices are low and fewer when high because the amount is fixed.'],
    ['CAGR', 'Compound Annual Growth Rate', 'The steady yearly growth rate that links a start value to an end value.'],
    ['XIRR', 'Extended Internal Rate of Return', 'Yearly return when money goes in at different dates, as in a SIP.'],
    ['Absolute return', '', 'Total % gained over the whole period, ignoring how long it took.'],
    ['Compounding', '', 'Earning returns on your earlier returns; the main reason starting early matters.'],
    ['Rule of 72', '', 'Divide 72 by the yearly return to get roughly the years to double your money.'],
    ['Inflation', '', 'The yearly rise in prices that reduces what your money can buy.'],
    ['Real return', '', 'Return after subtracting inflation (and tax).'],
    ['Asset allocation', '', 'How your money is split between equity, debt, gold and others.'],
    ['Rebalancing', '', 'Selling what grew and buying what lagged to return to your target split.'],
    ['Diversification', '', 'Spreading money across assets so one failure doesn’t sink you.'],
    ['Liquidity', '', 'How quickly you can turn an asset into cash without losing value.'],
    ['Volatility', '', 'How much prices swing up and down.'],
    ['Drawdown', '', 'The fall from a peak to a low point, for example a 30% drop.'],
    ['Risk appetite / risk capacity', '', 'How much loss you are willing to tolerate vs how much you can actually afford.'],
    ['Equity', '', 'Ownership in companies (shares, equity funds). Higher risk and higher long-term return.'],
    ['Debt instruments', '', 'Loans to governments or companies that pay interest (bonds, FDs, debt funds).'],
    ['Bond', '', 'A loan you give to a government or company in exchange for regular interest and your money back at maturity.'],
    ['Coupon', '', 'The interest a bond pays each year as a % of its face value.'],
    ['Face value / Par value', '', 'The amount printed on a bond or share, used to calculate interest and repayment.'],
    ['YTM', 'Yield to Maturity', 'The yearly return you earn if you hold a bond until it matures.'],
    ['Duration', '', 'How sensitive a bond’s price is to interest-rate changes. Longer duration means bigger swings.'],
    ['G-Sec', 'Government Security', 'A bond issued by the central government; considered free of default risk.'],
    ['SDL', 'State Development Loan', 'A bond issued by a state government.'],
    ['T-Bill', 'Treasury Bill', 'A short-term (up to 1 year) government security sold at a discount.'],
    ['NCD', 'Non-Convertible Debenture', 'A bond issued by a company. Check its credit rating before investing.'],
    ['Credit rating', '', 'A grade (AAA, AA… D) from agencies like CRISIL and ICRA showing the chance an issuer will repay.'],
    ['SGB', 'Sovereign Gold Bond', 'Government bond priced in grams of gold; pays 2.5% yearly interest and its maturity gain is tax-free.'],
    ['Gold ETF', '', 'A fund that holds gold and trades on the stock exchange.'],
    ['REIT', 'Real Estate Investment Trust', 'A listed fund that owns rent-earning properties and pays you part of the rent.'],
    ['InvIT', 'Infrastructure Investment Trust', 'A listed trust that owns roads, power lines and similar assets and pays income to unit-holders.'],
    ['AIF', 'Alternative Investment Fund', 'A privately pooled high-ticket fund (minimum ₹1 crore). Not meant for most people.'],
    ['PMS', 'Portfolio Management Service', 'A professional managing your individual stock portfolio (minimum ₹50 lakh).'],
    ['RIA', 'Registered Investment Adviser', 'A SEBI-registered adviser who charges a fee from you rather than commissions.'],
    ['Distributor / MFD', 'Mutual Fund Distributor', 'A person who sells funds and earns a commission from the fund house.'],
    ['Ponzi scheme', '', 'A fraud that pays old investors with money from new investors until it collapses.'],
    ['Pyramid / MLM', 'Multi-Level Marketing', 'A scheme where income depends on recruiting members rather than selling a real product.'],
    ['Crypto / VDA', 'Virtual Digital Asset', 'Digital tokens such as Bitcoin. Gains are taxed at a flat 30% with 1% TDS and no loss set-off.'],
    ['Blockchain', '', 'A shared digital ledger that records transactions across many computers.'],
    ['Seed phrase', '', '12 or 24 words that are the only key to a crypto wallet. Lose it and the money is gone.']
  ]);

  add('Mutual funds', [
    ['NAV', 'Net Asset Value', 'The price of one unit of a mutual fund on a day. A low NAV does not mean “cheap”.'],
    ['Unit', '', 'A share of a mutual fund. Units you hold × NAV = your investment value.'],
    ['AMC', 'Asset Management Company', 'The company that runs mutual funds (HDFC AMC, SBI Funds Management…).'],
    ['AMFI', 'Association of Mutual Funds in India', 'The industry body; publishes NAVs and runs investor awareness.'],
    ['AUM', 'Assets Under Management', 'The total money a fund or fund house manages.'],
    ['Scheme', '', 'A single mutual fund product, for example “Nifty 50 Index Fund”.'],
    ['Folio', '', 'Your account number with a fund house.'],
    ['Direct plan', '', 'A plan bought straight from the fund house with no distributor commission, so it has a lower expense ratio.'],
    ['Regular plan', '', 'A plan bought through a distributor; its higher expense ratio pays the commission.'],
    ['Growth option', '', 'Profits are reinvested, so NAV keeps rising. Best for building wealth.'],
    ['IDCW', 'Income Distribution cum Capital Withdrawal', 'The new name for “dividend” option; the payout comes out of your own NAV and is taxed at slab.'],
    ['TER', 'Total Expense Ratio', 'The yearly fee, as a % of assets, that the fund takes from NAV.'],
    ['Exit load', '', 'A fee when you sell units before a stated period (for example 1% within 1 year).'],
    ['Riskometer', '', 'SEBI’s six-level label from Low to Very High that shows a fund’s risk.'],
    ['Benchmark', '', 'The index a fund is compared with (Nifty 50, for example).'],
    ['Index fund / ETF', 'Exchange Traded Fund', 'A fund that simply copies an index, with very low cost.'],
    ['Tracking error', '', 'How far an index fund’s return differs from the index it follows. Lower is better.'],
    ['ELSS', 'Equity Linked Savings Scheme', 'A tax-saving equity fund with a 3-year lock-in, eligible under 80C in the old regime.'],
    ['Large / Mid / Small cap', '', 'Funds investing in the top 100 / next 150 / rest of listed companies by size. Smaller means riskier.'],
    ['Flexi-cap / Multi-cap', '', 'Funds that can invest across company sizes.'],
    ['Hybrid fund', '', 'A fund mixing equity and debt.'],
    ['Arbitrage fund', '', 'A low-risk fund that earns from price gaps, taxed like equity.'],
    ['Liquid fund', '', 'A debt fund investing for up to 91 days; used for parking emergency money.'],
    ['Overnight fund', '', 'A debt fund that lends for one day at a time; lowest risk among funds.'],
    ['Target maturity fund', '', 'A bond fund that holds until a set year so its return is more predictable.'],
    ['NFO', 'New Fund Offer', 'The launch period of a new fund. Not automatically a bargain.'],
    ['CAS', 'Consolidated Account Statement', 'One statement of all your mutual funds from CAMS and KFintech.'],
    ['CAMS / KFintech', '', 'The two registrars that keep the records of most mutual-fund holdings.'],
    ['MF Central', '', 'A common platform from CAMS and KFintech to invest and track all funds.'],
    ['Cut-off time', '', 'The deadline (generally 3 pm; 1:30 pm for liquid funds) for getting that day’s NAV.'],
    ['Lock-in', '', 'A period during which you cannot withdraw (ELSS: 3 years, PPF: 15 years, tax-saver FD: 5 years).'],
    ['FIFO', 'First In, First Out', 'The rule that the earliest units you bought are treated as sold first for tax.'],
    ['Tax harvesting', '', 'Selling units to use your yearly tax-free capital-gains limit and buying again.']
  ]);

  add('Stocks & markets', [
    ['Share / Stock', '', 'A small piece of ownership in a company.'],
    ['NSE / BSE', 'National / Bombay Stock Exchange', 'India’s two stock exchanges.'],
    ['Sensex / Nifty 50', '', 'Indexes that track the 30 / 50 largest companies; they show the market’s direction.'],
    ['Index', '', 'A basket of shares used to measure the market or a sector.'],
    ['SEBI', 'Securities and Exchange Board of India', 'The regulator of the stock market, mutual funds, brokers and advisers.'],
    ['Demat', 'Dematerialised account', 'The account that holds your shares and bonds in electronic form.'],
    ['Trading account', '', 'The account you use to place buy and sell orders; it links to your bank and demat.'],
    ['Broker', '', 'The licensed intermediary through which you trade (Zerodha, Groww, ICICI Direct…).'],
    ['DP', 'Depository Participant', 'The broker/bank that offers you the demat account. CDSL and NSDL are the depositories.'],
    ['CDSL / NSDL', '', 'The two companies that hold all electronic securities in India.'],
    ['ASBA', 'Applications Supported by Blocked Amount', 'The way to apply for IPOs: your money stays in your bank account, blocked until allotment.'],
    ['IPO', 'Initial Public Offering', 'A company selling its shares to the public for the first time.'],
    ['FPO / OFS', 'Follow-on Public Offer / Offer For Sale', 'Later share sales by a listed company or its promoters.'],
    ['DRHP / RHP', 'Draft / Red Herring Prospectus', 'The IPO document that discloses the business, risks and use of funds.'],
    ['Allotment', '', 'The shares assigned to you in an IPO.'],
    ['GMP', 'Grey Market Premium', 'An unofficial guess of IPO listing gain. It is unreliable.'],
    ['Listing', '', 'The day a company’s shares start trading on the exchange.'],
    ['Market cap', 'Market capitalisation', 'Share price × number of shares. The company’s total market value.'],
    ['EPS', 'Earnings Per Share', 'Company profit divided by number of shares.'],
    ['P/E', 'Price-to-Earnings ratio', 'Share price divided by EPS. A rough measure of how expensive a share is.'],
    ['P/B', 'Price-to-Book ratio', 'Share price divided by book value per share; mostly used for banks.'],
    ['ROE / ROCE', 'Return on Equity / Return on Capital Employed', 'How well a business turns shareholders’ money / total capital into profit.'],
    ['EBITDA', 'Earnings Before Interest, Taxes, Depreciation and Amortisation', 'A measure of operating profit before financing and accounting charges.'],
    ['PAT', 'Profit After Tax', 'Net profit the company keeps after tax.'],
    ['Dividend', '', 'A part of profit paid to shareholders. Taxable at your slab; TDS applies above ₹5,000.'],
    ['Dividend yield', '', 'Yearly dividend as a % of the share price.'],
    ['Bonus / Split', '', 'Free extra shares / dividing each share into smaller ones. Your total value stays the same.'],
    ['Buyback', '', 'A company buying back its own shares from shareholders.'],
    ['Promoter', '', 'The founders or controlling owners. “Promoter pledge” means they have borrowed against their shares, which is a risk.'],
    ['FII / FPI', 'Foreign Institutional / Portfolio Investor', 'Foreign funds investing in Indian markets. Heavy selling by them can push prices down.'],
    ['DII', 'Domestic Institutional Investor', 'Indian mutual funds, insurers and banks investing in the market.'],
    ['Bull / Bear market', '', 'Rising / falling market.'],
    ['Intraday', '', 'Buying and selling on the same day. Most intraday traders lose money.'],
    ['Delivery', '', 'Buying shares and holding them beyond the day; this is investing.'],
    ['F&O', 'Futures & Options', 'Derivative contracts with leverage and expiry. Roughly 9 in 10 retail traders lose money in them.'],
    ['Lot size', '', 'The fixed quantity in which a derivative contract is traded.'],
    ['Margin / Leverage', '', 'Borrowing from the broker to take bigger positions; magnifies both gains and losses.'],
    ['Circuit limit', '', 'The maximum % a share can rise or fall in a day before trading halts.'],
    ['Limit / Market / Stop-loss order', '', 'Buy or sell at your price / at the current price / automatically when a trigger price is hit.'],
    ['GTT', 'Good Till Triggered', 'An order that waits for months until your trigger price is reached.'],
    ['T+1', '', 'Settlement one working day after the trade; shares land in your demat the next day.'],
    ['STT', 'Securities Transaction Tax', 'A small tax charged on buying or selling shares and fund units on exchanges.'],
    ['LTCG / STCG', 'Long / Short Term Capital Gains', 'Tax on profit from selling an asset held for more / less than the qualifying period.'],
    ['Pledge / Margin pledge', '', 'Giving shares to the broker as security for trading margin.'],
    ['Block / Bulk deal', '', 'Very large transactions disclosed by the exchange.']
  ]);

  add('Insurance', [
    ['Premium', '', 'The amount you pay for an insurance policy.'],
    ['Sum assured / Sum insured', '', 'The maximum the insurer will pay: “sum assured” for life, “sum insured” for health and general.'],
    ['Term insurance', '', 'Pure life cover that pays your family if you die within the term; pays nothing on survival.'],
    ['Endowment / Money-back / ULIP', '', 'Insurance mixed with savings. Usually low returns and high charges; term plus investing works better.'],
    ['ULIP', 'Unit Linked Insurance Plan', 'A market-linked plan combining insurance and investment, with charges in the early years.'],
    ['Whole life', '', 'Cover for the entire life, much costlier than term.'],
    ['Riders / Add-ons', '', 'Optional extras attached to a policy: accidental death, critical illness, zero depreciation.'],
    ['Nominee / Beneficiary', '', 'The person who receives the claim money.'],
    ['Policyholder / Life assured', '', 'The person who owns the policy / the person whose life is covered.'],
    ['UIN', 'Unique Identification Number', 'The IRDAI product number of a policy; it tells you exactly which product and terms apply.'],
    ['IRDAI', 'Insurance Regulatory and Development Authority of India', 'The insurance regulator. Complaints can go to its Bima Bharosa portal.'],
    ['eIA', 'e-Insurance Account', 'A free account to hold all your policies in electronic form in one place.'],
    ['Free-look period', '', '15–30 days after buying a policy in which you can return it and get a refund (minus small charges).'],
    ['Grace period', '', 'Extra days after the due date to pay the premium and keep the policy alive (15 days for monthly, 30 days for others).'],
    ['Lapse / Revival', '', 'A policy ends when premiums aren’t paid; it can be revived within a window by paying dues.'],
    ['Surrender value', '', 'The amount you get if you cancel a savings policy early; often far less than you paid.'],
    ['Paid-up', '', 'Stopping future premiums while keeping a reduced cover.'],
    ['Maturity benefit', '', 'The amount paid when a savings policy ends.'],
    ['Claim settlement ratio', 'CSR', 'The % of claims an insurer pays out of the claims received. Also compare the amount-settled ratio.'],
    ['Repudiation', '', 'The insurer rejecting a claim. Ask for the reason in writing and appeal.'],
    ['Free-look / Cooling period', '', 'See free-look period.'],
    ['Contestability / 3-year clause', '', 'In the first years, insurers can investigate a death claim closely for non-disclosure.'],
    ['Moratorium (health)', '', 'After 60 months of continuous cover, claims cannot be refused for non-disclosure except for proven fraud.'],
    ['Waiting period', '', 'The time before certain diseases or pre-existing conditions are covered.'],
    ['Pre-existing disease (PED)', '', 'A condition you had before buying the policy; covered only after the waiting period.'],
    ['Co-pay', '', 'The % of every claim you pay yourself.'],
    ['Deductible', '', 'The amount you pay first in a year before the insurer pays (used in super top-up).'],
    ['Sub-limit', '', 'A cap on specific costs such as room rent or cataract surgery.'],
    ['Room-rent limit', '', 'A daily cap on room charges; crossing it reduces the whole claim proportionately.'],
    ['Floater policy', '', 'One health cover shared by the whole family.'],
    ['Top-up / Super top-up', '', 'Cheap extra cover that pays only after a deductible is crossed.'],
    ['Cashless', '', 'The insurer pays the network hospital directly; you pay only non-covered items.'],
    ['Reimbursement', '', 'You pay the hospital and claim the money back later with bills.'],
    ['TPA', 'Third Party Administrator', 'A company that processes health claims for insurers.'],
    ['Pre-authorisation', '', 'The insurer’s approval for cashless treatment before or during admission.'],
    ['Network hospital', '', 'A hospital that has a cashless arrangement with your insurer.'],
    ['Day-care procedure', '', 'A treatment needing less than 24 hours in the hospital, covered by most policies.'],
    ['Domiciliary', '', 'Treatment at home when a patient can’t be moved.'],
    ['Restoration / Reload', '', 'The sum insured is refilled after you use it.'],
    ['No-claim bonus / NCB', '', 'A bonus for a claim-free year: extra cover in health, or discount in motor.'],
    ['Portability', '', 'Switching insurer for your health policy while keeping waiting-period credit.'],
    ['Critical illness cover', '', 'A lump sum paid when you are diagnosed with a listed serious illness.'],
    ['PA', 'Personal Accident', 'Cover for accidental death and disability.'],
    ['Third-party (TP) cover', '', 'Mandatory motor cover for damage or injury you cause to others.'],
    ['Own damage (OD)', '', 'Motor cover for your own vehicle.'],
    ['IDV', 'Insured Declared Value', 'The current market value of your vehicle for insurance; the most you receive in a total loss or theft.'],
    ['Zero depreciation', '', 'A motor add-on that pays full part cost without cutting for age.'],
    ['Constructive total loss', '', 'Repairs would cost more than about 75% of IDV so the insurer pays out the vehicle’s IDV.'],
    ['Surveyor', '', 'The insurer’s assessor who inspects damage and approves claims.'],
    ['PM-JAY / Ayushman Bharat', 'Pradhan Mantri Jan Arogya Yojana', 'Government health cover up to ₹5 lakh per family for eligible households.'],
    ['PMJJBY / PMSBY', 'PM Jeevan Jyoti Bima Yojana / PM Suraksha Bima Yojana', 'Very cheap government life and accident cover bought through banks every year.'],
    ['APY', 'Atal Pension Yojana', 'A government pension scheme that pays a fixed pension of ₹1,000–5,000 a month from age 60.'],
    ['MWP Act', 'Married Women’s Property Act', 'A policy under it protects the money for wife and children from the policyholder’s creditors.']
  ]);

  add('Income tax', [
    ['PAN', 'Permanent Account Number', 'Your 10-character tax ID. Needed for banking, investing and filing returns.'],
    ['TAN', 'Tax Deduction and Collection Account Number', 'Number an employer or deductor needs to deduct and deposit TDS.'],
    ['ITR', 'Income Tax Return', 'The form you file to report your income and tax each year. ITR-1 for simple salary cases.'],
    ['AY / FY', 'Assessment Year / Financial Year', 'FY is the year you earn (1 April to 31 March); AY is the next year in which you file.'],
    ['Tax year', '', 'The new name for FY and AY under the Income-tax Act, 2025 (from 1 April 2026).'],
    ['CBDT', 'Central Board of Direct Taxes', 'The body that makes income-tax rules and issues circulars.'],
    ['Old / New regime', '', 'The old regime has many deductions with higher rates; the new regime has lower rates and almost no deductions.'],
    ['Slab', '', 'An income band that is taxed at a particular rate.'],
    ['Standard deduction', '', 'A flat deduction from salary income for everyone, without proofs.'],
    ['Rebate 87A', '', 'A tax rebate that makes tax zero up to a set income.'],
    ['Cess', 'Health and Education Cess', '4% extra on the tax and surcharge.'],
    ['Surcharge', '', 'Extra tax on very high incomes (above ₹50 lakh).'],
    ['Gross / Net / Taxable income', '', 'Total earnings / after some deductions / the amount on which tax is actually charged.'],
    ['Deduction / Exemption', '', 'An amount you subtract from income before tax / income that is not taxed at all.'],
    ['80C', 'Section 80C', 'Old-regime deduction up to ₹1.5 lakh for EPF, PPF, ELSS, life insurance, tuition fees, home-loan principal and more.'],
    ['80CCD(1B)', '', 'An extra ₹50,000 deduction for your own NPS contribution (old regime).'],
    ['80CCD(2)', '', 'Deduction for your employer’s NPS contribution; allowed in both regimes.'],
    ['80D', 'Section 80D', 'Deduction for health-insurance premiums and preventive check-ups.'],
    ['80E', 'Section 80E', 'Deduction for all the interest on an education loan for up to 8 years.'],
    ['80G', 'Section 80G', 'Deduction for donations to approved charities.'],
    ['80TTA / 80TTB', '', 'Deduction on savings-account interest (₹10,000; ₹50,000 for seniors).'],
    ['24(b)', 'Section 24(b)', 'Deduction for home-loan interest up to ₹2 lakh on a self-occupied home (old regime).'],
    ['HRA', 'House Rent Allowance', 'A salary part for rent. Old-regime exemption is the least of: actual HRA, rent − 10% of basic, and 50%/40% of basic.'],
    ['LTA', 'Leave Travel Allowance', 'Tax-free travel allowance for two journeys in a four-year block (old regime).'],
    ['Form 16', '', 'The certificate from your employer showing salary paid and TDS deducted in the year.'],
    ['Form 26AS', '', 'A statement of all tax deducted or paid against your PAN.'],
    ['AIS / TIS', 'Annual Information Statement / Taxpayer Information Summary', 'Everything the tax department knows about your income: salary, interest, dividends, trades, property. Match your return with it.'],
    ['TDS', 'Tax Deducted at Source', 'Tax cut by the payer (employer, bank) before paying you. It is credited against your final tax.'],
    ['Form 15G / 15H', '', 'A declaration (below 60 / seniors) asking the bank not to deduct TDS because your income is below the taxable limit.'],
    ['Advance tax', '', 'Tax you pay in instalments during the year (15 Jun, 15 Sep, 15 Dec, 15 Mar) if your liability after TDS is ₹10,000 or more.'],
    ['Self-assessment tax', '', 'The balance tax you pay before filing the return.'],
    ['Challan 280 / ITNS 280', '', 'The payment form for advance tax and self-assessment tax.'],
    ['E-verification', '', 'Confirming your filed return via Aadhaar OTP or net banking within 30 days; without it the return is not valid.'],
    ['Belated / Revised / Updated return', 'ITR-U', 'A late return / a corrected return / a return filed up to 48 months later to add missed income.'],
    ['Refund', '', 'Money the department pays back when your TDS and advance tax exceed your tax.'],
    ['Intimation 143(1)', '', 'The department’s first processing notice, comparing your return with its data.'],
    ['Scrutiny / Notice 142(1), 148', '', 'Detailed enquiry or reopening of a return. Respond on the portal within the deadline.'],
    ['Capital gains', '', 'Profit from selling an asset such as shares, mutual funds, gold or property.'],
    ['Indexation', '', 'Adjusting the purchase price for inflation to reduce taxable gain; now allowed only in specific property cases.'],
    ['Grandfathering', '', 'A rule that treats shares bought before 1 Feb 2018 as if bought at their 31 Jan 2018 price, if higher.'],
    ['Section 54 / 54EC / 54F', '', 'Exemptions from long-term gains if you reinvest in a house or specified bonds within time limits.'],
    ['Set-off / Carry forward', '', 'Using a loss to reduce other gains in the year / carrying it to later years (up to 8) if the return was filed on time.'],
    ['Clubbing of income', '', 'Adding income from assets you gave to your spouse or minor child to your own income.'],
    ['Presumptive taxation 44AD / 44ADA', '', 'A simple scheme for small businesses / professionals: tax on a fixed % of turnover without detailed books.'],
    ['Schedule VDA', '', 'The section of the return where crypto gains are reported.'],
    ['Perquisite', '', 'A taxable benefit from your employer such as a car or housing.'],
    ['Form 26QB / 16B', '', 'The challan-cum-statement for TDS on property purchase / the certificate given to the seller.'],
    ['Section 194-IA', '', '1% TDS a buyer deducts when paying ₹50 lakh or more for property.'],
    ['Annual value / NAV of property', '', 'The notional rent of a house on which house-property income is calculated.'],
    ['Tax audit 44AB', '', 'Compulsory audit of accounts when a business crosses a turnover limit.'],
    ['Black money / Benami', '', 'Undisclosed income / property held in another person’s name; both attract heavy penalties.']
  ]);

  add('Salary & PF', [
    ['CTC', 'Cost to Company', 'The total yearly amount the employer spends on you, including items you don’t receive monthly.'],
    ['Gross salary', '', 'Pay before deductions.'],
    ['Net / Take-home / In-hand', '', 'What reaches your bank account after deductions.'],
    ['Basic pay', '', 'The core part of salary, normally 40–50% of CTC; PF and gratuity are based on it.'],
    ['DA', 'Dearness Allowance', 'A cost-of-living allowance, mainly for government employees.'],
    ['Special allowance', '', 'A flexible taxable part of salary.'],
    ['Variable pay / Bonus', '', 'Performance-linked pay that is not guaranteed.'],
    ['Joining bonus / Notice buy-out', '', 'A one-time payment to join / paying the employer to skip the notice period.'],
    ['Professional tax', '', 'A small state tax on salary, up to ₹2,500 a year.'],
    ['EPF', 'Employees’ Provident Fund', 'A retirement fund to which you and your employer each contribute 12% of basic.'],
    ['EPFO', 'Employees’ Provident Fund Organisation', 'The body that runs EPF and the pension scheme.'],
    ['UAN', 'Universal Account Number', 'A permanent 12-digit PF number that stays with you across jobs.'],
    ['VPF', 'Voluntary Provident Fund', 'Extra contribution beyond 12% at the same EPF rate.'],
    ['EPS', 'Employees’ Pension Scheme', 'The pension part of employer’s contribution (8.33%); a pension needs 10 years of service.'],
    ['EDLI', 'Employees’ Deposit Linked Insurance', 'A free life cover given to EPF members.'],
    ['ESI / ESIC', 'Employees’ State Insurance', 'Medical and cash benefits for employees earning up to ₹21,000 a month.'],
    ['Gratuity', '', 'A lump sum from the employer after 5 years of service. Formula: last basic × 15/26 × years.'],
    ['Leave encashment', '', 'Money for unused leave paid when you leave or retire.'],
    ['Full & Final (F&F)', '', 'The last settlement of salary, leave and dues when you leave a job.'],
    ['Appraisal / Increment / Hike', '', 'A review of pay / the raise / its percentage.'],
    ['ESOP / RSU', 'Employee Stock Option Plan / Restricted Stock Unit', 'Company shares given as a benefit. Taxed as a perquisite when you exercise or when they vest.'],
    ['Vesting', '', 'The schedule on which promised shares or benefits become yours.'],
    ['Cliff', '', 'The initial period (often 1 year) before any vesting starts.'],
    ['NPS', 'National Pension System', 'A low-cost retirement account where part must buy an annuity at 60.'],
    ['PRAN', 'Permanent Retirement Account Number', 'Your NPS account number.'],
    ['PFRDA', 'Pension Fund Regulatory and Development Authority', 'The regulator of NPS and pension funds.'],
    ['Annuity', '', 'A product that pays you a fixed income for life in return for a lump sum.'],
    ['Corpus', '', 'The total accumulated sum, such as a retirement corpus.'],
    ['SWR', 'Safe Withdrawal Rate', 'The % of your corpus you can draw each year without running out (3–4% is common).'],
    ['FIRE', 'Financial Independence, Retire Early', 'Building enough investments that work becomes optional.']
  ]);

  add('Property', [
    ['Sale deed / Conveyance deed', '', 'The registered document that transfers ownership. Keep the original safe.'],
    ['Agreement to sell', '', 'A pre-sale contract with terms and price; it is not ownership.'],
    ['Title / Title deed', '', 'The legal proof that you own a property.'],
    ['Chain of title / Mother deed', '', 'The unbroken sequence of earlier deeds back to the original owner.'],
    ['EC', 'Encumbrance Certificate', 'Official proof that the property has no mortgage or legal dues for the period checked.'],
    ['Khata / Patta / Khatauni / 7/12', '', 'Local land or property tax records showing the owner. Names differ by state.'],
    ['A-khata / B-khata', '', 'Karnataka terms: A-khata is a fully legal property; B-khata is not fully approved and often can’t get loans.'],
    ['Mutation', '', 'Updating revenue or municipal records to the new owner after a purchase.'],
    ['Stamp duty', '', 'A state tax on a property transfer, usually 4–8% of value.'],
    ['Registration charges', '', 'The fee for registering the deed at the Sub-Registrar (about 0.5–1%).'],
    ['Circle rate / Guidance value / Ready reckoner', '', 'The minimum value set by the government for stamp duty. Duty is on the higher of this and the deal price.'],
    ['Sub-Registrar', '', 'The government office where property deeds are registered.'],
    ['Franking / e-stamp', '', 'Paying stamp duty electronically.'],
    ['RERA', 'Real Estate (Regulation and Development) Act', 'A law and state authorities that protect home buyers; check a project’s RERA registration number.'],
    ['Carpet / Built-up / Super built-up area', '', 'Usable floor area inside walls / carpet plus walls / built-up plus shared areas. RERA prices on carpet area.'],
    ['OC', 'Occupancy Certificate', 'Certificate that a building is complete and fit to live in. Without it, living or getting a loan can be a problem.'],
    ['CC', 'Commencement / Completion Certificate', 'Permission to start building / confirmation that it was built as approved (check which is meant).'],
    ['FSI / FAR', 'Floor Space Index / Floor Area Ratio', 'How much built area is allowed on a plot.'],
    ['Layout approval / Sanctioned plan', '', 'The authority’s approval of the layout or building plan.'],
    ['NA / Conversion', 'Non-Agricultural', 'Permission to use farmland for housing or business.'],
    ['Freehold / Leasehold', '', 'You own the land outright / you hold it for a number of years from the owner or authority.'],
    ['Joint development / Society share certificate', '', 'A building built on shared land / proof that you are a member of a housing society.'],
    ['Maintenance / Sinking / Corpus fund', '', 'Monthly charges to run the building / amounts collected for major repairs.'],
    ['Possession letter', '', 'The builder’s letter handing the flat to you.'],
    ['Snag list', '', 'A list of defects you note before taking possession.'],
    ['Defect liability period', '', 'The 5 years after possession in which the builder must fix structural defects free (RERA).'],
    ['Power of Attorney (POA)', '', 'A document letting someone act for you. It is not ownership; avoid buying on POA alone.'],
    ['Gift deed / Will / Release deed', '', 'Ways to transfer property without sale: during life / after death / when a co-owner gives up a share.'],
    ['Rental yield', '', 'Yearly rent as a % of the property’s price (often 2–3% for homes).'],
    ['Property tax', '', 'A yearly municipal tax on owning a property.'],
    ['Rent agreement / Leave and licence', '', 'A written rent contract; keep it for HRA claims.'],
    ['Security deposit', '', 'Refundable amount you give a landlord, often 2–10 months’ rent.'],
    ['TDR', 'Transferable Development Rights', 'Rights to build extra area that can be sold to another developer.']
  ]);

  add('Vehicle', [
    ['RC', 'Registration Certificate', 'The legal document that proves registered ownership of the vehicle and lists its details.'],
    ['Chassis number / VIN', 'Vehicle Identification Number', 'A 17-character code stamped on the frame; the permanent identity of the vehicle.'],
    ['Engine number', '', 'The number stamped on the engine. It must match the RC.'],
    ['RTO / RTA', 'Regional Transport Office / Authority', 'The government office that registers vehicles and issues licences.'],
    ['Parivahan / VAHAN / Sarathi', '', 'The national portals for vehicle records / licences. mParivahan is the app.'],
    ['DL', 'Driving Licence', 'The licence to drive; keep a DigiLocker copy.'],
    ['LL', 'Learner’s Licence', 'A temporary licence while you learn to drive.'],
    ['HSRP', 'High Security Registration Plate', 'A tamper-proof number plate with a hologram and a unique laser code.'],
    ['PUC', 'Pollution Under Control certificate', 'Proof that your vehicle’s emissions are within limits; must be renewed.'],
    ['Form 20', '', 'Application for vehicle registration.'],
    ['Form 21 / 22', '', 'Sale certificate / road-worthiness certificate issued by the dealer for a new vehicle.'],
    ['Form 28', '', 'Application for NOC when moving a vehicle to another state.'],
    ['Form 29 / 30', '', 'Notice of transfer of ownership / application for transfer of ownership; both must be filed in a sale.'],
    ['Form 34 / 35', '', 'Adding / removing the bank’s hypothecation on the RC.'],
    ['Hypothecation', '', 'The lender’s name on the RC until the loan is cleared.'],
    ['BH series', 'Bharat series', 'A registration that stays valid across states without re-registration.'],
    ['On-road price', '', 'Ex-showroom price plus road tax, registration, insurance, HSRP and other charges: what you actually pay.'],
    ['Ex-showroom price', '', 'The vehicle price before taxes and other costs.'],
    ['Road tax / Life tax', '', 'A state tax paid once (or yearly for commercial vehicles) for using the vehicle on roads.'],
    ['Fitness certificate (FC)', '', 'Certificate that a vehicle is roadworthy; required for commercial and older vehicles.'],
    ['Challan', '', 'A traffic fine. Unpaid challans stay with the vehicle and can block a transfer.'],
    ['e-Challan', '', 'An electronic traffic fine sent based on camera or police records.'],
    ['Odometer', '', 'The meter that records kilometres travelled. Tampering is a common used-vehicle fraud.'],
    ['EV', 'Electric Vehicle', 'A vehicle run by a battery; often has lower road tax and running cost.'],
    ['ICE', 'Internal Combustion Engine', 'A petrol or diesel vehicle.'],
    ['CNG', 'Compressed Natural Gas', 'A cheaper cleaner fuel option for cars.'],
    ['Depreciation', '', 'The yearly fall in a vehicle’s value.'],
    ['20/4/10 rule', '', 'A car guideline: at least 20% down, loan up to 4 years, total vehicle cost up to 10% of income.']
  ]);

  add('GST & business', [
    ['GST', 'Goods and Services Tax', 'The single indirect tax on goods and services in India.'],
    ['GSTIN', 'GST Identification Number', 'The 15-character GST registration number of a business.'],
    ['CGST / SGST / IGST', 'Central / State / Integrated GST', 'CGST and SGST are charged within a state, IGST between states.'],
    ['ITC', 'Input Tax Credit', 'Credit for GST you paid on business purchases against GST you collect.'],
    ['HSN / SAC', 'Harmonised System of Nomenclature / Services Accounting Code', 'Codes that classify goods / services for GST.'],
    ['GSTR-1 / GSTR-3B', '', 'Monthly or quarterly GST returns: sales details / summary with tax payment.'],
    ['E-way bill', '', 'An electronic document needed to move goods worth more than ₹50,000.'],
    ['E-invoice', '', 'A government-registered invoice, mandatory above a turnover limit.'],
    ['Composition scheme', '', 'A simple GST option for small businesses paying a fixed % of turnover.'],
    ['Reverse charge (RCM)', '', 'The buyer, not the seller, pays the GST for certain supplies.'],
    ['Proprietorship / Partnership / LLP / Pvt Ltd', '', 'Common business structures; LLP and Pvt Ltd give limited liability.'],
    ['MCA / ROC', 'Ministry of Corporate Affairs / Registrar of Companies', 'The authority that registers companies and receives their filings.'],
    ['CIN / DIN / DSC', '', 'Company number / Director number / Digital Signature Certificate.'],
    ['MOA / AOA', 'Memorandum / Articles of Association', 'The founding documents of a company.'],
    ['FSSAI', 'Food Safety and Standards Authority of India', 'The licence needed to make or sell food.'],
    ['Shop & Establishment licence', '', 'A state licence to run a shop or office.'],
    ['Trademark / IPR', 'Intellectual Property Rights', 'Legal protection for a brand name or logo.'],
    ['Startup India / DPIIT', '', 'The recognition scheme that gives eligible startups tax and compliance benefits.'],
    ['Break-even', '', 'The sales level at which revenue equals total costs.'],
    ['Contribution margin', '', 'Selling price minus variable cost per unit.'],
    ['Gross margin / Net margin', '', 'Profit after direct costs / after all costs, as a % of revenue.'],
    ['Working capital', '', 'Cash tied up in running the business: receivables + inventory − payables.'],
    ['Runway', '', 'How many months you can run before cash ends.'],
    ['Burn rate', '', 'Cash spent each month.'],
    ['CAC / LTV', 'Customer Acquisition Cost / Lifetime Value', 'What it costs to win a customer / the total profit that customer brings.'],
    ['Receivables / Payables', '', 'Money customers owe you / money you owe suppliers.'],
    ['Invoice / Purchase order (PO)', '', 'A bill for what you sold / an order from a buyer.'],
    ['Cash flow', '', 'Money actually coming in and going out, which can differ from profit.'],
    ['Balance sheet / P&L', 'Profit & Loss statement', 'What the business owns and owes / its income and expenses over a period.'],
    ['Bootstrapping', '', 'Funding a business from your own savings and profits.'],
    ['Angel / VC', 'Venture Capital', 'Investors who fund early-stage startups in return for shares.'],
    ['Term sheet', '', 'A summary of an investment deal’s main terms.'],
    ['Valuation / Dilution', '', 'What the business is worth / the drop in your ownership % when new shares are issued.']
  ]);

  add('Government & regulators', [
    ['RBI', 'Reserve Bank of India', 'Regulates banks, NBFCs, payments and currency.'],
    ['SEBI', 'Securities and Exchange Board of India', 'Regulates markets, mutual funds, brokers and advisers.'],
    ['IRDAI', 'Insurance Regulatory and Development Authority of India', 'Regulates insurance.'],
    ['PFRDA', 'Pension Fund Regulatory and Development Authority', 'Regulates NPS and pension funds.'],
    ['NPCI', 'National Payments Corporation of India', 'Runs UPI, RuPay and other retail payment systems.'],
    ['FIU-IND', 'Financial Intelligence Unit – India', 'Receives suspicious-transaction reports; crypto exchanges must register with it.'],
    ['CERT-In', 'Indian Computer Emergency Response Team', 'The agency that handles cyber incidents.'],
    ['1930 / cybercrime.gov.in', '', 'The national cyber-fraud helpline and complaint portal. Call at once if you are scammed.'],
    ['SCORES', 'SEBI Complaints Redress System', 'SEBI’s portal to complain about brokers and listed companies.'],
    ['Bima Bharosa', '', 'IRDAI’s portal to complain about insurers.'],
    ['Ombudsman', '', 'A free, independent officer who resolves complaints against banks (RBI) or insurers.'],
    ['CMS / RBI Integrated Ombudsman', '', 'The single RBI portal to complain about banks, NBFCs and payment providers.'],
    ['DigiLocker', '', 'A government app to store official documents (Aadhaar, PAN, RC, licence) that are legally valid.'],
    ['Aadhaar / UIDAI', 'Unique Identification Authority of India', 'The 12-digit ID number and the body that issues it. Use the masked Aadhaar when sharing.'],
    ['e-Aadhaar / Masked Aadhaar', '', 'A digital copy of Aadhaar / a copy showing only the last 4 digits.'],
    ['Aadhaar-PAN link', '', 'Mandatory linking of Aadhaar with PAN; an unlinked PAN becomes inoperative.'],
    ['Jan Dhan / Jan Suraksha', '', 'Government drives for bank accounts / low-cost insurance and pension.'],
    ['PPF', 'Public Provident Fund', '15-year tax-free government savings scheme with ₹1.5 lakh yearly limit.'],
    ['SSY', 'Sukanya Samriddhi Yojana', 'A high-rate tax-free savings scheme for a girl child.'],
    ['SCSS', 'Senior Citizens’ Savings Scheme', 'A 5-year scheme for people 60+ with quarterly interest and a ₹30 lakh limit.'],
    ['NSC / KVP', 'National Savings Certificate / Kisan Vikas Patra', 'Fixed-rate post-office certificates.'],
    ['POMIS', 'Post Office Monthly Income Scheme', 'A 5-year scheme that pays monthly interest.'],
    ['PM-Kisan / PMAY / PMMY', '', 'Farmer income support / housing for all (interest subsidy on home loans) / Mudra loans.'],
    ['PM-SYM / eShram', '', 'Pension and registration for informal workers.'],
    ['Vidya Lakshmi / NSP', 'National Scholarship Portal', 'Government portals to compare education loans / apply for scholarships.'],
    ['DBT', 'Direct Benefit Transfer', 'Government money sent straight to your bank account.'],
    ['Budget / Finance Act', '', 'The Union Budget in February proposes tax changes; the Finance Act makes them law.'],
    ['Monetary policy / MPC', 'Monetary Policy Committee', 'The RBI committee that sets the repo rate every two months.'],
    ['GDP / CPI / WPI', 'Gross Domestic Product / Consumer / Wholesale Price Index', 'Size of the economy / retail inflation / wholesale inflation.'],
    ['Fiscal deficit', '', 'The gap between government spending and income that it must borrow.']
  ]);

  add('Everyday money words', [
    ['Asset', '', 'Anything you own that has value.'],
    ['Liability', '', 'Anything you owe.'],
    ['Net worth', '', 'Assets minus liabilities.'],
    ['Income / Expense', '', 'Money coming in / going out.'],
    ['Savings rate', '', 'The share of income you save.'],
    ['Budget', '', 'A plan that gives every rupee a job.'],
    ['50/30/20 rule', '', '50% needs, 30% wants, 20% savings and debt.'],
    ['Sinking fund', '', 'Money set aside monthly for a known future cost such as insurance or a vehicle service.'],
    ['Emergency fund', '', 'Cash equal to 3–12 months of expenses for job loss and shocks.'],
    ['Opportunity cost', '', 'What you give up by choosing one use of money over the next best.'],
    ['Time value of money', '', 'A rupee today is worth more than a rupee later.'],
    ['Present value / Future value', 'PV / FV', 'What a future sum is worth today / what today’s money will be worth later.'],
    ['Lifestyle creep', '', 'Spending more every time your income rises.'],
    ['Debt snowball / avalanche', '', 'Paying the smallest balance first / the highest-interest balance first.'],
    ['Good debt / Bad debt', '', 'Borrowing that builds value (education, home) / borrowing for things that lose value.'],
    ['Bear trap / Pump and dump', '', 'Fake signals meant to make you buy or sell at the wrong time.'],
    ['Haircut', '', 'A reduction taken in the value of something, or a loss imposed on lenders.'],
    ['Blue chip', '', 'A large, long-established, financially strong company.'],
    ['Penny stock', '', 'A very cheap, risky and often manipulated share.'],
    ['Margin of safety', '', 'Buying at a price well below what you think something is worth.'],
    ['Hedge', '', 'An investment that protects against loss elsewhere, such as gold.'],
    ['Liquidity crunch', '', 'A situation where there is not enough cash to meet payments.'],
    ['Default', '', 'Failing to repay a loan or bond.'],
    ['Insolvency / IBC', 'Insolvency and Bankruptcy Code', 'Legal process when a person or firm cannot pay debts.'],
    ['Will / Probate', '', 'Your written wishes for your property after death / court certificate that a will is valid.'],
    ['Legal heir / Succession certificate', '', 'A relative entitled to inherit / a court document proving who the heirs are.'],
    ['HUF', 'Hindu Undivided Family', 'A separate tax entity of a family; it gets its own exemption and slabs.'],
    ['Trust / Trustee', '', 'An arrangement in which a trustee manages assets for beneficiaries.'],
    ['Fiduciary', '', 'A person legally bound to act in your best interest, such as a fee-only adviser.'],
    ['Commission / Fee-only', '', 'Pay received from the product maker (can bias advice) / pay received only from you.'],
    ['Mis-selling', '', 'Selling a product that doesn’t suit the buyer by hiding or twisting facts.'],
    ['Fine print / MITC', '', 'The small-type terms and conditions where costs and exclusions hide.'],
    ['Cooling-off', '', 'A short period in which you can cancel without penalty.'],
    ['Auto-renewal', '', 'A subscription or policy that renews itself and charges you unless you cancel.'],
    ['GST invoice', '', 'The tax bill you need for warranty, input credit and returns.'],
    ['Ledger / Passbook entry', '', 'A written record of money in and out.'],
    ['Digital footprint', '', 'The trail of information about you online, which scammers use.'],
    ['Phishing / Vishing / Smishing', '', 'Fraud by fake emails or sites / phone calls / SMS to steal your details.'],
    ['SIM swap', '', 'A fraud in which criminals get a duplicate of your SIM to receive your OTPs.'],
    ['Digital arrest', '', 'A scam in which fake officers threaten you on video call and demand money. No agency does this.'],
    ['Rug pull', '', 'A crypto scam where the developers drain the money and vanish.']
  ]);

  FOS.jargonCount = () => J.length;

  /* ---------- the "Money Words A–Z" page ---------- */
  FOS.tools = FOS.tools || {};
  const esc = (t) => String(t).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const key = (e) => e.t.replace(/[^A-Za-z0-9]/g, '').toLowerCase();
  FOS.tools.jargon = function (root) {
    let cat = '', q = '', short = false, letter = '';
    const first = (e) => { const c = e.t.replace(/[^A-Za-z0-9]/g, '').charAt(0).toUpperCase(); return /[0-9]/.test(c) ? '#' : c; };
    const letters = [...new Set(J.map(first))].sort();
    root.innerHTML = `<div class="card"><h3>${J.length} money words and short forms, explained simply</h3><p class="muted">From “KYC” and “IFSC” to “LTCG”, “UIN” and “HUID”: every word you meet in banks, cards, loans, investing, insurance, income tax, salary, property, vehicles, GST and government schemes. Type in the box, pick a topic, or tap a letter.</p>
      <input class="input" id="jw-q" type="search" placeholder="Search a word or full form: KYC, repo, nominee, HRA…" aria-label="Search words" autocomplete="off">
      <div class="chips" id="jw-c"><button class="chip on" data-c="">All topics</button>${FOS.JARGON_CATS.map((c) => `<button class="chip" data-c="${esc(c)}">${esc(c)}</button>`).join('')}</div>
      <div class="chips" id="jw-l"><button class="chip on" data-l="">A–Z</button>${letters.map((l) => `<button class="chip" data-l="${l}">${l}</button>`).join('')}</div>
      <label class="check"><input type="checkbox" id="jw-s"> Short forms only (abbreviations like EMI, KYC, TDS)</label></div>
      <p class="muted" id="jw-n"></p><div id="jw-list" class="jw-list"></div>`;
    const gl = {}; (FOS.GLOSSARY || []).forEach((g) => { gl[g[0].replace(/[^A-Za-z0-9]/g, '').toLowerCase()] = g[0]; });
    const isShort = (e) => !!e.full || /^[A-Z0-9/&()\-. ]{2,12}$/.test(e.t);
    const draw = () => {
      const t = q.toLowerCase().trim();
      const list = J.filter((e) => (!cat || e.cat === cat) && (!short || isShort(e)) && (!letter || first(e) === letter) && (!t || (e.t + ' ' + e.full + ' ' + e.m).toLowerCase().includes(t)))
        .sort((a, b) => key(a).localeCompare(key(b)) || a.t.localeCompare(b.t));
      root.querySelector('#jw-n').textContent = list.length + ' of ' + J.length + ' shown';
      root.querySelector('#jw-list').innerHTML = list.length ? list.map((e) => `<article class="jw-item"><div class="jw-h"><b class="jw-t">${esc(e.t)}</b>${e.full ? `<span class="jw-f">${esc(e.full)}</span>` : ''}<span class="pill">${esc(e.cat)}</span></div><p>${esc(e.m)}</p>${gl[key(e)] ? `<a class="jw-more" href="#/glossary?t=${encodeURIComponent(gl[key(e)])}">Formula and example in the Glossary →</a>` : ''}</article>`).join('') : '<p class="muted">Nothing matches. Try a shorter word, or clear the filters.</p>';
    };
    root.querySelector('#jw-q').oninput = (e) => { q = e.target.value; draw(); };
    root.querySelector('#jw-s').onchange = (e) => { short = e.target.checked; draw(); };
    root.querySelector('#jw-c').onclick = (e) => { const b = e.target.closest('[data-c]'); if (!b) return; cat = b.dataset.c; root.querySelectorAll('#jw-c .chip').forEach((x) => x.classList.toggle('on', x === b)); draw(); };
    root.querySelector('#jw-l').onclick = (e) => { const b = e.target.closest('[data-l]'); if (!b) return; letter = b.dataset.l; root.querySelectorAll('#jw-l .chip').forEach((x) => x.classList.toggle('on', x === b)); draw(); };
    const w = /[?&]w=([^&]+)/.exec(location.hash); if (w) { q = decodeURIComponent(w[1]); root.querySelector('#jw-q').value = q; }
    draw();
  };
})();
